### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by mbuk** [axllent/mailpit#1]
Hi @axllent thanks for releasing this.
Can I +1 for basic auth support?

**Comment by axllent** [comment]
I had actually already started work on this feature yesterday, so you can likely expect it in the next couple few days 👍

**Comment by mbuk** [comment]
Amazing 🙇

**Comment by axllent** [comment]
I'll leave this open until it is actually implemented and tested :)

**Comment by axllent** [comment]
@mbuk I've just release 0.0.5 which contains Basic Auth support. Please test and report any issues, thanks.

**Comment by mbuk** [comment]
I'll check it out today!

Thanks

**Comment by mbuk** [comment]
@axllent noticed that the auth file spec has -a, ---auth-file string when looking at the help
but the documentation says --auth-file <path-to-file>

Triple hyphen in exec but double in docs.

Other that minor point about working perfectlt!

Tested changing the hash type
Tested multiple users
Tested file missing
Tested permissions restricted to file.
All behaves as expected!

Thank you!

**Comment by axllent** [comment]
Thanks for the feedback & testing! You are absolutely right, that's a typo in the three `---` - I will fix that which will be included in the next release tomorrow.

**Comment by sandervanzutphen** [comment]
Are the different basicAuth users supposed to result in split inboxes? That does not seem to be te case atm.
This becouse the -h parameters describes the -m parameter as "Max number of messages per mailbox (default 500)", emphatis on the 'per mailbox' part.

**Comment by axllent** [comment]
No it does not, it is all just access to one mabox. Initially I considered that, but to get something like that working would require email filtering, rules, permissions, and a bunch more. It just became too complicated for a tool intended only for developer testing.

**Comment by axllent** [comment]
@mbuk Just to keep you in the loop as I know you're using this feature, in the latest (0.1.0) release `-a` and `--auth-file` have been deprecated and replaces with just `--ui-auth-file` (no short flag). I did this because Mailpit now also has the option for SMTP authentication which is called `--smtp-auth-file` - so it made the most sense to rename that original flag.

**Comment by mbuk** [comment]
@axllent Cheers 👍
