### ISSUE TITLE
mailpit as a proxy

### ISSUE THREAD

**Issue by renannprado** [axllent/mailpit#104]
We rely fully on mailhog (not for long) as our mock in lower environments.
However, we also run tests with a real SMTP server from time to time.

We're soon replacing mailhog with mailpit and I would like to know if there's a feature where mailpit acts like a **proxy**, meaning that it would take the e-mail, record, store it, etc; and pass over to the underlying (real) SMTP server. So that then we can see the e-mail even when we don't have access to the recipient's e-mail box.

Do we have such a feature?

**Comment by tonyswu** [comment]
There was another feature request similar to this: https://github.com/axllent/mailpit/issues/29#issuecomment-1502010175. I haven't gotten around to test it myself, but like yourself we'll be phasing out mailhog pretty soon.

**Comment by axllent** [comment]
I'd say 29 was a request for the exact same thing - you want Mailpit to receive an email, store a copy, and automatically send/forward that email on to another SMTP server. This functionality was added recently and is documented on https://github.com/axllent/mailpit/wiki/SMTP-relay

Please let me know if this is what you were after?

**Comment by renannprado** [comment]
> I'd say 29 was a request for the exact same thing - you want Mailpit to receive an email, store a copy, and automatically send/forward that email on to another SMTP server. This functionality was added recently and is documented on https://github.com/axllent/mailpit/wiki/SMTP-relay
> 
> Please let me know if this is what you were after?

Amazing! Thanks for the reply.

In this case, I'm closing this issue until I get the change to try it out.

**Comment by renannprado** [comment]
FYI I've tried out and it works like a charm 😄 .

**Comment by Yahyaali1** [comment]
I went over the wiki. Can anyone of you please share a sample yml file for configuration of this proxy ?

**Comment by axllent** [comment]
@Yahyaali1 I assume by proxy you mean that Mailpit automatically relays all messages via a preconfigured SMTP server? If so, first ensure your configuration is set up correctly ([docs](https://github.com/axllent/mailpit/wiki/SMTP-relay)), and  when Mailpit is running you are able to "release" messages via the web UI. Assuming that is working (your SMTP server accepts the messages), you can add the `--smtp-relay-all` flag to your Mailpit startup options (or `MP_SMTP_RELAY_ALL=true` to the environment, depending on how you start Mailpit) and it should work.

**Comment by Yahyaali1** [comment]
Thank you @axllent.
