### ISSUE TITLE
Add Readme section to check if everything is working fine

### ISSUE THREAD

**Issue by jeromelaurens** [axllent/mailpit#105]
The README would benefit a lot a section for testing it.

For example : 

### Testing if mailpit is working with mailpit sendmail command

1. Create a text file containing the headers and the body of the email, for example, `email.txt`:

       From: sender@example.com
       To: recipient@example.com
       Subject: Email Subject

       This is the body of the email.
       It can contain multiple lines of text.

2. Next, run the following command in the terminal:

       mailpit sendmail -t < email.txt

   This command uses the `-t` flag, which tells `sendmail` to read the "To", "Cc", and "Bcc" headers from the file to determine the recipients.

3. Check on the UI : the email should be there

**Comment by axllent** [comment]
Thanks for the suggestion. Given that there are several ways to use "sendmail" (using `mailpit sendmail...`, symlinking mailpit to sendmail, using a system-installed sendmail binary, not to mention setting up PHP as an example), I think I'll simplify the README and add a link to a Wiki post (which I haven't created yet). If I don't do this then half the README will be just about testing sendmail :) Please leave this with me and I'll get this done soon, thanks.

**Comment by axllent** [comment]
Please have [a read of this](https://github.com/axllent/mailpit/wiki/Sendmail---testing) and let me know if you think that is helpful, thanks?

**Comment by jeromelaurens** [comment]
The section is very good, but, in my humble opinion would benefit to be in a dedicated section or in a getting started or, better, at the end of the installation section of README (or link to the wiki in the installation section)
My use case was : 
- the team has pain with mailhog, I want to have a quick look at mailpit before trying it in a projet as a replacement.
- So I installed it with homebrew (I'm on MacOS)
- I wanted to see as quick as possible some emails in th UI to check the UI (ordering, search, new email arriving...)
- mail app was awful to setup only for sending without a pop account
- stackoverflow says that you can setup the command line but you have to parameter some POSIX config files... I don't know how to do it
- so I was searching some command line, remembered the old days of sendmail
- I didn't know that sendmail was in macOS, neither how to configure it (found it only at the end after having sent email with mapit sendmail)
- I had read the README and it was not obvious that I could use the sendmail replacement as a tool to check mailpit since the section was named "configuring sendmail", I was on the installation setup and wanted to finish it by sending to it an email
- I read some issues to check if the projet was living and one of them mentionned that you could use mailpit sendmail to send emails "as explained in the README". On my point of view, that was not explained
- then only I could figure out that I could use mailpit sendmail to send quickly my first email to mailpit

**Comment by axllent** [comment]
Hi. I'm not sure you checked that link I posted? It is to a new dedicated Wiki page that explains it in more detail, including your suggestion. I wanted to check this new page before I update the README to point to this new wiki page.

**Comment by jeromelaurens** [comment]
Yes I checked the link, of course, I even answered : "The section is very good"
The title is "SendMail testing".
When you are a newcomer, your use case is not "Sendmail testing" but "Check installation".
You don't care about `sendmail` specifically, you just want to finish the installation and send quickly an email and see it in the UI.
With this documentation organization, again as a newcomer, you'll never find it.
It is just a feedback from a newcomer, maybe it is obvious to you, but not for a newcomer, I can assure.
Feel free to do whatever you want.

**Comment by axllent** [comment]
My apologies, I obviously misunderstood. As a technical person I definitely would not call it "Check installation" as that suggests information regarding the installation of Mailpit on various systems - which I definitely do not want to cover (there are just too many different setups / platforms etc) . Your point about non-technical people finding the relevant information is duly noted though, and I will update the main README to be shorter and clearer, linking to the correct documentation. Thank you for your advise!
