### ISSUE TITLE
IDEA: Add selection box and sort features

### ISSUE THREAD

**Issue by Florent4782** [axllent/mailpit#11]
Hello,

just trying to improve this already awesome job. 

This could be nice to be able to select multiple mails to delete them at once.

Also, been able to sort the emails by column (sender, date, size, etc) would be great too.

Thanks,
Florent

**Comment by axllent** [comment]
Thanks for the suggestions. I agree, multiple email selections would be a handy feature (though would be limited to the visible emails on the screen). I will at some point implement this.

Re: column sorting - whilst a nice feature (I have thought of this before), I decided against it for technical reasons. Firstly Mailpit streams new incoming emails directly to the browser, so automatically handles sorting (by the reversed order) and pagination (new messages are simply pushed to the top of the list when on the first page). If I was to implement column sorting, the browser would have no idea of the order to display them when new messages arrive, and trying to re-calculate that via the database on each received message isn't feasible as it would require a complex database lookup on each incoming message, and a browser request to "refresh". For a single message this isn't an issue, but when 50 emails per second are coming in.... Secondly, fields like size, received date, subject and to/from values are stored within a JSON field within the database, so sorting by these via a database lookup would be very CPU & disk intensive. A long story short, this isn't possible unfortunately.

**Comment by axllent** [comment]
@Florent4782 Multi-select has been added to the 1.0.0 release. In order not to clutter the UI, this is a "hidden" feature which can be used by using shift-click or ctrl-click combinations on the current view in the message list.
