### ISSUE TITLE
Chaos Monkey

### ISSUE THREAD

**Issue by StanislavPrusac** [axllent/mailpit#110]
Does Mailpit have any functionality like there is in MailHog, Jim is the Chaos Monkey?
If not, do you plan to add some kind of Chaos Monkey?

Jim is the MailHog Chaos Monkey, inspired by Netflix:
https://github.com/mailhog/MailHog/blob/master/docs/JIM.md

**Comment by axllent** [comment]
Currently no, Mailpit does not contain any of that chaos monkey functionality, nor was this planned either. Much (if not all) of the SMTPD functionality in MailHog was built from scratch, possibly for this exact reason (to introduce bandwidth limiting and other failure at various parts of the process etc), which I suspect heavily impacted its speed. Mailpit's focus is on performance & speed, and it doesn't use home-grown SMTP solutions - so it's likely not possible to add all of those features.

Before I rule anything out, I would love to understand what you are using Jim for, and which features specifically you're relying on?

**Comment by richardstubbs** [comment]
@axllent No so much chaos but programmatically being about to set the response codes:

API endpoint to activate a 5xx response error code and a UI toggle switch to do the same.

Mailpit is a killer app for developers but for full end to end tests and edge case errors it cant be used yet.

The use case being testing as 250/251/252 code will always delver mail, but in full automated testing one of the tests can be how the code being tested handles a 5xx error from the SMTP service, so the test framework makes the API call to to enable a 500 response then runs the test, then again turning off a the 500 response when the test has run, but equally useful a user can toggle this in the ui to test a 5xx response in the code, and yes a full set of 5xx response would be future feature.

**Comment by axllent** [comment]
@richardstubbs This sounds to me to be a far better solution than just randomly (though there is something to be said for that too, but makes testing far more difficult if you need to expect an exact error). I suppose that given the right CLI arguments, MailHog could do that too by setting a particular feature to 100(%), and the others to 0.

Either way though, I can't see any way of **artificially** returning an error while using the current [smtpd](https://github.com/mhale/smtpd) module, so the only way would be able to do that is to include and modify that code within the Mailpit code. I think that ideally one could set just the 5xx response code and get a default message, and optionally also set the error message. The question I have though is that I assume that different errors happen at different parts of the receive process, eg: 530 (Authentication required) wouldn't be returned at the beginning of the connection, and 554 (Message too big for system) would only happen after the message has been sent (or potentially while in transit), making this a very complicated. I think that ideally (from an implementation perspective) the error would always happen in the same place within the SMTP connection, however I don't know if that would be suitable. 

Clearly you have far more knowledge than I do of full automated SMTP testing, so maybe you can tell me if that really matters (if the artificial error is always returned at the same place, eg: right after the SMTP connection starts, or should different errors always happen in different places (HELO, EHLO, MAIL, RCPT, DATA etc)?

**Comment by axllent** [comment]
Chaos functionality has just been released in the latest version, [see this comment](https://github.com/axllent/mailpit/issues/402#issuecomment-2614154786).

**Comment by richardstubbs** [comment]
Excellent I will check it out.

**Comment by robstoll** [comment]
looks like by now it is included https://mailpit.axllent.org/docs/integration/chaos/
