### ISSUE TITLE
Helm- chart for MailPit

### ISSUE THREAD

**Issue by Jeremiahkip** [axllent/mailpit#111]
@axllent  First of all, MailTip works great. Thank you for putting in the time and effort.

Just wondering if there are any future plans to create helm charts for this project: something similar to this https://github.com/codecentric/helm-charts/tree/master/charts/mailhog

Best regards.

**Comment by jouve** [comment]
I just started at chart https://github.com/jouve/charts/tree/main/charts/mailpit

**Comment by axllent** [comment]
Thanks @jouve 👍 I think I was right, that looks far too complicated (considering I don't use helm) and personalised (startup options) for me to maintain as a general installer.

**Comment by Jeremiahkip** [comment]
> @Jeremiahkip Thanks for using Mailpit. I have no plans to implement and maintain charts for Mailpit, mainly because I don't use helm charts and have absolutely no experience with it.
> 
> Based on what I see on that link however, it appears anyone such as yourself can create their own helm chart repo. I really don't know what is involved in creating or maintaining this, but it is an option (you can maintain your own?). There are just too many different installers and deployment processes for any developer to maintain, so I pick the main (widely used) ones.

Thanks for getting back that quick. No worries! I do understand and yes anyone can create a helm chart repo themselves. Just thought I'd ask just in case there was one already out there somewhere

**Comment by Jeremiahkip** [comment]
> I just started a chart there https://github.com/jouve/charts/tree/main/charts/mailpit

That's really nice of you @jouve 
Thanks for sharing 👍 I'll try it out at sometime soon

**Comment by janquijano** [comment]
@jouve good job man. any chance you could add an option to use an existing secret?

```
        auth:
          enabled: true
          existingSecret: mailpit-secret
```

**Comment by jouve** [comment]
@janquijano  I published a new release with existing secret support https://github.com/jouve/charts/tree/main/charts/mailpit#existing-secrets
