### ISSUE TITLE
Support push notifications

### ISSUE THREAD

**Issue by jonaskuske** [axllent/mailpit#113]
Would be super cool if mailpit would support push (background) notifications using service workers, so that you don't have to keep it open in a tab in order to check if mailing works.

Would be happy to contribute the feature if you agree to adding this functionality :)

**Comment by axllent** [comment]
I believe this relates to your other question #112. I'm interested, but before you start trying to implement anything, could you please provide me a link regarding this type approach, as I thought it was now a redundant browser feature which had long been removed (due to abuse)?

**Comment by jonaskuske** [comment]
Not closely related, #112 has value even without push functionality.

> as I thought it was now a redundant browser feature which had long been removed (due to abuse)

No, it's very much alive! Browser vendors did a lot of work on the permissions model, prompt UI and heuristics to discover spam over the last years so the API is less prone to abuse. In fact, Apple shipped support for the Web Push API [to desktop Safari last year with Safari 16](https://webkit.org/blog/12945/meet-web-push/) and [to iPhones and iPads two months ago with 16.4](https://webkit.org/blog/13966/webkit-features-in-safari-16-4/). (but only allowed for websites that are added to the homescreen there) Also related APIs like the Badging API to show e.g. the unread count badge on the app icon of a web app.

It's not removed and also not redundant or deprecated. https://developer.mozilla.org/en-US/docs/Web/API/Push_API

**Comment by axllent** [comment]
Thanks for the info. Unfortunately I don't have enough time at the moment to investigate this properly. I would really appreciate if you could tell me:
1. What changes would need to happen to allow a browser to connect to Mailpit for push notifications? This would replace the existing browser notifications I assume?
2. What changes may be needed in Mailpit (HTTPD) in order to communicate with the browser? I assume it's not just a matter of using the existing websocket.

Thanks!

**Comment by jonaskuske** [comment]
Sure! The flow is as follows:

On first server start, create a public/private key pair for use with the Voluntary Application Server Identification for Web Push (VAPID) Protocol. Pass the public key to the frontend, could be a member of `appInfo`.

On first frontend start, register a service worker (small JS background script that is run for specific events) that listens for push events:

```js
self.addEventListener('push', (data) => {
  self.showNotification(data)
}) 
```

When a user turns on notifications, call `pushManager.subscribe()` on the frontend, passing in the public key. This returns a subscription object containing a unique endpoint for the respective browser's messaging service. (e.g. something like `https://firebase-cloud-messaging.com/sOmE-r4nd0m-ID` in Chrome) Pass the endpoint to the server and store it.

Now when the server receives a new mail, create a JSON object for the notification, sign it with the private key created in step one and send it to the stored endpoint via POST request. Even with the site not opened, this makes the browser run the service worker script and trigger the `push` event, so the notification is shown.

[`webpush-go`](https://github.com/SherClockHolmes/webpush-go) offers `GenerateVAPIDKeys` and `SendNotification` functions that can be used for the server portion.

**Comment by axllent** [comment]
@jonaskuske Sorry to keep you waiting. I currently have a lot on my plate, which is taking preference over me looking further into this. Unfortunately this feature just keeps getting pushed to the back of the queue as it's a nice-to-have, which I believe requires quite a bit of work to implement properly. At this stage all I can say is "not planned", although I'm not saying "no". If you wanted to have a crack at this then I'd be open to a PR, but I'm cautious about this feature becoming more of a hindrance to users who may not want this at all (you're the first to request it). There is a good change that I do not understand the requirements properly, but it comes back to the "I don't have enough time right now to look at this" comment.
