### ISSUE TITLE
WSS Calls - Always use the IP:PORT instead of the current UI origin

### ISSUE THREAD

**Issue by sgalinski** [axllent/mailpit#126]
Problem: I'm proxying the UI to have a more readable name for internal reasons. The WSS calls fail, because of a wrong destination.

![image](https://github.com/axllent/mailpit/assets/122370/53723f37-96e9-4098-b4b6-24a9cd55a988)

This seems to be the problematic code. 

			wsproto + "://" + document.location.host + document.location.pathname + "api/events"

This could also be a configuration option. I hope that this can be implemented. Mailpit is a real great successor of Mailhog. :)

**Comment by axllent** [comment]
The secure websocket connections are using the same host as the web UI, so the issue/solution here is not that you need to manually override the wss path, it is that your proxy isn't configured properly to proxy websockets. Please see the first section on https://github.com/axllent/mailpit/wiki/Troubleshooting and let me know if this solves your issue?

**Comment by sgalinski** [comment]
Thanks. This works pretty well after some research including your mentioned links.

BTW: Here is a chef cookbook for Mailpit. It contains the installation, auto-start with systemd and the apache proxy configuration. Maybe helpful for someone else: https://gitlab.sgalinski.de/chef-cookbooks/mailpit
The cookbook depends a little bit on other ones like https://gitlab.sgalinski.de/chef-cookbooks/normal_site and https://gitlab.sgalinski.de/chef-cookbooks/ubuntu_base

I hope that this helps someone else as I didn't found any concrete implementation myself.

**Comment by axllent** [comment]
Thanks for the feedback / links @sgalinski, and glad to hear you got it sorted. Unfortunately documenting the exact steps isn't possible because everyone has a different configurations to proxy, and there are many solutions that can be used to proxy http traffic. I'm closing this as resolved.
