### ISSUE TITLE
(Feature request) Support multiple inboxes

### ISSUE THREAD

**Issue by supriyo-biswas** [axllent/mailpit#128]
Hey, thanks for this very useful project :)

Is it possible for Mailpit to support multiple inboxes? The use case for this is I'd like to have multiple apps that send their emails to the same instance of Mailpit but different inboxes, so that automated testing scripts can fetch the correct email through the API having to follow conventions to separate out the other projects' emails.

**Comment by axllent** [comment]
Thanks, I'm really glad you like it! No sorry, multiple inboxes is not on the roadmap. Please see #86 and #115  for the same question and some of the reasoning behind this decision.

As a work-around for your use-case, you could technically auto-tag your messages (assuming you can filter by something unique, or can add a `X-Tags` header to your messages) and then search by tag.
