### ISSUE TITLE
Improve Documentation to show how to send an HTML format file as an email

### ISSUE THREAD

**Issue by maza256** [axllent/mailpit#129]
The documentation currently only shows how to send a plain text email. It would be wonderful if it could be used to send a fully formatted HTML file.

**Comment by axllent** [comment]
The example in the documentation is purely intended to briefly test whether sendmail & Mailpit is working. Fully formatted HTML emails are typically not sent from the commandline, but rather send via applications using (for example) PHP, Ruby, Java, Go, etc which often then use sendmail to relay the message. This falls completely outside of the scope of Mailpit and/or the documentation.

If you do specifically wish so send an HTML email via the commandline, a simple Google search returns the following example:
```shell
echo "From: me@xyz.com
To: them@xyz.com
MIME-Version: 1.0
Content-Type: multipart/alternative;
boundary='PAA08673.1018277622/server.xyz.com'
Subject: Test HTML e-mail.

This is a MIME-encapsulated message

--PAA08673.1018277622/server.xyz.com
Content-Type: text/html

<html> 
<head>
<title>HTML E-mail</title>
</head>
<body>
<a href='http://www.google.com'>Click Here</a>
</body>
</html>
--PAA08673.1018277622/server.xyz.com
" | sendmail -t
```

**Comment by ilhamsyahids** [comment]
Hello @axllent 

I'm trying to send email with `multipart/alternative` like as you do, however it appear as Text in web ui and not showing anything, I use latest `axllent/mailpit:v1.23` and with only config `MP_SMTP_AUTH_ACCEPT_ANY`, `MP_SMTP_AUTH_ALLOW_INSECURE`. Can you help me for this?

Thanks

<img width="408" alt="Image" src="https://github.com/user-attachments/assets/130610e1-8cef-4d2d-bcaa-370430f96dd6" />

**Comment by axllent** [comment]
@ilhamsyahids That would be because that example does not contain a text part. Try something like this:

```
echo "From: Example Company <news@example.com>
To: Joe User <joe.u@example.net>
Date: Sat, 21 May 2011 17:40:11 +0300
Subject: Multipart message example
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary=asdfghjkl

--asdfghjkl
Content-Type: text/plain; charset=utf-8

This is the text part.

--asdfghjkl
Content-Type: text/html; charset=utf-8

<body>
This is the <b>HTML</b> part.
</body>

--asdfghjkl--
" | sendmail -t
```

**Comment by ilhamsyahids** [comment]
I see, I know the issue was. Apparently, mailpit cannot detect it html and text part if the the boundary has `<>`, please see the image below:

<img width="617" alt="Image" src="https://github.com/user-attachments/assets/1fdea204-1b7f-42e4-aee2-1837b385f274" />

```sh
echo "From: Example Company <news@example.com>
To: Joe User <joe.u@example.net>
Date: Sat, 21 May 2011 17:40:11 +0300
Subject: Multipart message example
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary=MIME_boundary_<asdfghjkl@example.net>

--MIME_boundary_<asdfghjkl@example.net>
Content-Type: text/plain; charset=utf-8

This is the text part.

--MIME_boundary_<asdfghjkl@example.net>
Content-Type: text/html; charset=utf-8

<body>
This is the <b>HTML</b> part.
</body>

--MIME_boundary_<asdfghjkl@example.net>--
" | mailpit sendmail -t
```

I also tried when its not contain the prefix (`boundary=<asdfghjkl@example.net>`), the result was email not appear in the mailpit.

I confirmed in gmail, both are works:

<img width="528" alt="Image" src="https://github.com/user-attachments/assets/a4c3a95e-ea4d-4fc2-bfba-3812dd12ce94" />
<img width="697" alt="Image" src="https://github.com/user-attachments/assets/420d0970-b3c8-402d-8eca-2355b9a75fac" />


Can you confirm on your end? @axllent

**Comment by axllent** [comment]
@ilhamsyahids I would suggest that it is because you're using invalid characters. I don't think`<` & `>` are legally allowed. See https://stackoverflow.com/a/147467

**Comment by ilhamsyahids** [comment]
Thats make sense, thanks for your confirmation @axllent
