### ISSUE TITLE
Suggest:Support for CR Line Break Code in Text Emails

### ISSUE THREAD

**Issue by SuzuTakahiro** [axllent/mailpit#135]
In actual email clients like Outlook, there are cases where the carriage return (CR) is supported as a line break code for text emails.

Do you have any plans to support the CR line break code in text emails in Mailpit?

**Comment by axllent** [comment]
Hi @SuzuTakahiro. Are these emails (with just a CR line break) being generated by Outlook, or just being read in Outlook?

If I understand you correctly, the issue you are experiencing is that the Text format in the webmail UI shows all your content on one line?

Emails must follow the very clear standard set in [RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322#section-2.1) which states:

> Messages are divided into lines of characters.  A line is a series of characters that is delimited with the two characters carriage-return and line-feed; that is, the carriage return (CR) character (ASCII value 13) followed immediately by the line feed (LF) character (ASCII value 10).

Mailpit is a tool used for testing both email delivery and the email content/structure itself. I do not think it's a good idea to create work-arounds to support CR line break code when emails clearly should also include a LF. It woulds to me like Mailpit is doing exactly what it should - showing you there is a problem with your email and/or delivery agent.

Can you please tell me what is generating these emails, and how they are being delivered to Mailpit?

**Comment by SuzuTakahiro** [comment]
Thank you for the detailed explanation.

I mistakenly assumed that line breaks with carriage returns (CR) were the standard because they were used in applications like Outlook.
I understand and acknowledge that what you're saying is correct.
That was very educational for me.


I was sending the emails created through a program to Mailpit,Outlook, and other platforms for verification.

I was very nervous about my first issue, but thank you for explaining it to me in detail.

**Comment by axllent** [comment]
Don't be nervous! Feedback is always good 👍
