### ISSUE TITLE
Can't connect unauthenticated

### ISSUE THREAD

**Issue by rubencallewaert** [axllent/mailpit#145]
Hi,

We are trying to run mailpit in a container unauthenticated so that we can connect without having to provide any authentication info.

We set the following env variables:
```
  MP_SMTP_AUTH_ACCEPT_ANY: 1
  MP_SMTP_AUTH_ALLOW_INSECURE: 1
```

But still get errors like these from the client:
'Mail command failed: 550 Unauthenticated senders not allowed'

When providing no authentication information, any ideas?

**Comment by axllent** [comment]
This should be working. Using the combination of `MP_SMTP_AUTH_ACCEPT_ANY` & `MP_SMTP_AUTH_ALLOW_INSECURE` should do what you are expecting - effectively allow any connection whether it is authenticated or not. What does `docker logs <your-container-name>` report? You should see something like:
```
INFO[2023/07/19 08:23:32] [smtpd] enabling all auth (insecure)         
INFO[2023/07/19 08:23:32] [smtpd] starting on 0.0.0.0:1025             
INFO[2023/07/19 08:23:32] [http] starting server on http://localhost:8025/
```

**Comment by rubencallewaert** [comment]
You are correct and there was a subtle misconfiguration on the the client that caused the issue. Mailpit works as expected. Apologies for the redundant report.

**Comment by axllent** [comment]
Excellent, thanks for the confirmation :+1:
