### ISSUE TITLE
MP_WEBROOT is ignored in the API-Documentation

### ISSUE THREAD

**Issue by christian-scheible** [axllent/mailpit#147]
I have set **MP_WEBROOT** to _mailcatcher_. However when I am visiting http://localhost/mailcatcher/api/v1/ the documentation shows:

**API Server http://localhost**

and if I try to test a request using the **TRY** button, the request fails as it doesn't append mailcatcher to the request.

So it tries `http://localhost/api/v1/info` instead of `http://localhost/mailcatcher/api/v1/info`

**Comment by axllent** [comment]
You are absolutely right - currently the swagger config does not take the current webroot into consideration. I'll need to think of a solution for this as the `swagger.json` spec file for the API (used in the docs you are referring to) is embedded in the application, and not dynamically generated based on startup arguments.

**Comment by christian-scheible** [comment]
@axllent, that was quick, thank you! It's not a blocker for me, as I am now using Postman to explore the API. However, I believe honoring the environment variable would make it easier for other users.

**Comment by axllent** [comment]
@christian-scheible This should be fixed now in the latest release :rocket:  Please feel free to re-open this ticket if it's not working as you expected.

**Comment by christian-scheible** [comment]
@axllent Thank you for the quick solution. It is now working as expected.
