### ISSUE TITLE
Feature Request: Broken Link Checker

### ISSUE THREAD

**Issue by mansoorkhan96** [axllent/mailpit#151]
@axllent Thanks for creating this amazing tool.

This is a feature request to add an automated link checker that verifies all the links in an email are valid and return a 200 status code. Helpful to catch broken links while testing.

Thanks a ton ❤️

**Comment by axllent** [comment]
That is an interesting idea! I'll give it some serious thought as I'm sure most wouldn't want all links automatically scanned by default (depending what types of mail they are scanning), but the ability to do a manual check could be a potential solution.

**Comment by mansoorkhan96** [comment]
@axllent Right, may be you could add some of sort of optional setting or configuration that defaults to false. So that users that need to scan broken links do not have to do it manually. It just runs for them every-time and give them an indication or warning sign.

I really appreciate your efforts towards betterment of this tool 
Thanks.

**Comment by axllent** [comment]
Yes, that was pretty much my thinking too. Default off, with the option to run it manually, and a toggle to run it automatically (like the HTML checker does).

**Comment by axllent** [comment]
I have just released this feature in v1.8.2. Please have a play and let me know what you think?

**Comment by mansoorkhan96** [comment]
I have updated to latest and have checked. Looks good.

Thank you @axllent 

<img width="1070" alt="image" src="https://github.com/axllent/mailpit/assets/51432274/170a8f53-37ee-4c69-80ac-097e76e3ddfb">
