### ISSUE TITLE
Wiki Update: Content Security Policy

### ISSUE THREAD

**Issue by junyang-chin** [axllent/mailpit#165]
Since v1.8.0 remote stylesheets is not blocked by default but this behaviour is not updated in the [wiki](https://github.com/axllent/mailpit/wiki/UI-security-policies#content-security-policy)

I have provided a draft paragraph that you could use and edit
>The Mailpit UI does have a strict Content-Security-Policy header which prevents your browser from loading any remote content, except for images and stylesheets. This means that your web browser will block all iframes, inline & remote JavaScript within the UI.
>
>To disable remote remote CSS stylesheets & fonts (eg: Google Fonts) use the `--block-remote-css-and-fonts` runtime option

**Comment by axllent** [comment]
Great catch, thanks @junyang-chin! I have updated the wiki with your suggestion :)
