### ISSUE TITLE
Feature request: receive emails via a mock SES API

### ISSUE THREAD

**Issue by crdoconnor** [axllent/mailpit#167]
I know this is probably reaching a little, but I thought I'd bring it up anyway :)

I found myself trying to use mailpit with an app that sent emails via SES recently and felt sad that that prevented me from using it, and I had to look at inferior tools like https://github.com/askrella/aws-ses-mock

**Comment by axllent** [comment]
You are right @crdoconnor, it is reaching 😂 I'll explain why... what you're basically asking is for Mailpit to provide an SES-compatible server endpoint. Whilst I'm sure this is technically possible (ie: that other project you mentioned does it), it requires a full implementation and maintenance of that specific functionality in the Mailpit codebase, and integration with authentication etc. This is just for SES, but then what about the other 20 or so popular (similar) services like Mailgun? I would get flooded for requests for x y and z. It gets really complicated very quickly, adds a huge development load on me, increases the Mailpit binary size, and is a nightmare to maintain.

The alternative (and more feasible) option is to build yourself an "SES-to-SMTP proxy", that would be similar to that project, but which then delivers the emails to Mailpit via SMTP.

**Comment by crdoconnor** [comment]
Yeah, I figured as much :)

**Comment by axllent** [comment]
Cool :) I'd encourage you to build your own SES-to-SMTP-proxy - I'm sure it's not that difficult as you appear to know python and I'm sure AWS have some python SDKs if needed. From what I could tell (based on the project you linked), it could be as simple as a HTTPD server which accepts a JSON post with some data - and then "forwarding" that email via SMTP.

**Comment by crdoconnor** [comment]
Yeah, I could and I probably will next time. I think it's probably not quite as good a solution because it's another weighty service (on top of the 6-7 that are already running in parallel) which means those already CPU and RAM hungry tests become even more hungry. It would also be super nice for mailpit to be 100% a one stop shop for all mail testing needs after it's already 90% there.

I understand the desire to maintain the conceptual integrity of mailpit, though, and as you said, if you do SES why not mailgun as well.

**Comment by axllent** [comment]
I think you'd be surprised just how little overhead a single proxy httpd service uses in terms of resources. I understand your point about wanting Mailpit to do it all, but it's just not feasible to build and maintain such a variety of mail transfer protocols properly. I've also had requests to add POP3 and IMAP support too, but with the same result ultimately. There's no reason a pop service couldn't be integrated with the Mailpit API, and the same applies to IMAP. This way somebody else also gets to invest their time, knowledge and skills too.

**Comment by axllent** [comment]
And thanks for the sponsorship, I really appreciate it ❤️
