### ISSUE TITLE
feature request: ability to send emails via api to mimic mailchannels

### ISSUE THREAD

**Issue by avnav0** [axllent/mailpit#168]
would be great to be able to see html

**Comment by axllent** [comment]
@avnav0 I'm not sure what functionality exactly you are asking to mimic? Based on your original message (before you edited it), it sounded like you were asking for a mailchannels-compatible API endpoint (clone) to be built into Mailpit, but you then edited that message so now I really don't know if that is what you actually meant. If that is what you are asking, then I suggest you refer to my response & explanation on #167 which was asking for a similar feature (but for a completely different service).

**Comment by avnav0** [comment]
@axllent hey yeah sorry, i was originally trying to see if it would be possible to implement an API - but then just ended up writing my own little server.  then i was running into an issue with having mailpit render html.
but that's been solved.

two issues unrelated.

for mailchannels, i ended up just taking the same object that would go to their api and parsing it before sending it off to mailpit.

**Comment by axllent** [comment]
Glad to hear it, thanks for the feedback!
