### ISSUE TITLE
Feature request: Delete or tag after release

### ISSUE THREAD

**Issue by mk-git** [axllent/mailpit#169]
I came across mailpit a few days ago while looking for a mailtrap with a release option. So I can check mails before they leave the building (or go to the customer). The release works flawlessly.

My feature request: would it be possible to add an option to automatically delete a mail after release or automatically tag it after release?

Version: Mailpit (v1.9.2) as container

**Comment by axllent** [comment]
Glad to hear it's working well for you @mk-git! I assume you are manually releasing individual messages here? If so, then I'm sure I could add a delete option (tickbox) to the UI when you release a message. Would that work for you?

**Comment by mk-git** [comment]
Hi. Yes I release the mails manually.  
Yes, a way to delete directly would be great. But maybe for one or the other case it would be better to set a tag, e.g. "released". Then it remains flexible for everyone.

If you delete you don't need the tag. But vice versa, if you release but don't delete (or forget to click on it) nobody knows that it was already released once. then the tag would help to identify which ones were already released.

For me the "delete on release" function would already help, but I think together with a tag it is more flexible.

**Comment by axllent** [comment]
While I always like the idea of flexibility, I do not think that setting a pre-configured tag is exactly "flexible", plus it introduces additional code logic that needs to be maintained, and included in yet another environment variable / cli flag: this user wants it called "X", the next wants it called "Y", the next wants it to replace all tags with "B", the next want it to append to the existing tags with "W" etc. One of the downsides of maintaining a popular project is any change you make has a far greater impact & thus reaction :)

I will however add a tickbox to optionally delete the message after release as this doesn't modify the existing functionality much. If you would like to add a tag, then you can always just add that once the modal is closed.

**Comment by axllent** [comment]
I have just released v1.9.4 which includes the ability to delete a message after release (tickbox, default off). Please have a test and let me know if this works for you? Thanks!

**Comment by mk-git** [comment]
Works flawlessly. many thanks for the fast integration. ❤

**Comment by axllent** [comment]
You're welcome :)
