### ISSUE TITLE
Feature request: Set auth credentials from env variables

### ISSUE THREAD

**Issue by Leny1996** [axllent/mailpit#173]
Like in the topic - it could be great to provide login and password using env variables (separate for UI and SMTP).
For example:
```
MP_UI_AUTH_USER=admin
MP_UI_AUTH_PASSWORD=admin (in all supported formats)
```
In the code - if those variables are present, then do not use AUTH_FILE.

**Comment by axllent** [comment]
I'll see what I can do here 👍

**Comment by ulken** [comment]
This would align perfectly with my setup and make things easier on my end as well 👍  Let me know if I can help.

**Comment by axllent** [comment]
I have just released v1.9.4 which includes the ability to set both the web UI and SMTP credentials via the `MP_UI_AUTH` & `MP_SMTP_AUTH` environment  variables. The credentials are a space-separated string with the exact same `user1:password1 user2:password2` formats documented in [the wiki](https://github.com/axllent/mailpit/wiki/Basic-authentication). Obviously plain text passwords are not recommended :) Please have a test and let me know if this works for you? Thanks!

**Comment by ulken** [comment]
On fire 🔥 

I'll give it a try later today and report back.

**Comment by ulken** [comment]
Sorry for the late report. The weekend happaned and then other things popped up (as they tend to do...). I start looking at it yesterday and then the deployment environment failed on me etc. etc.

Anyhow, I've now tested it with the UI and it worked flawlessly 👌 

One thing: how do you sign out? 😅  Clear cookies/local storage?

**Comment by axllent** [comment]
That's great news (that it's working, not deployment failures lol). It's basic auth, you don't log out, you just close your browser. That's about it, nothing special, no cookies. There is localstorage which is just some preferences, but not credentials.

I'm closing this issue as it appears to have resolved the original request 👍
