### ISSUE TITLE
When switching from Light/Auto to Dark theme, email text is black on dark.

### ISSUE THREAD

**Issue by mbomb007** [axllent/mailpit#182]
1. Open an email, viewing the HTML (the email body, not the HTML Source).
1. Set the theme setting to Auto (light) or Light. 
1. Refresh the page.
1. Set the setting to Dark.
1. It will look like the below image, until you switch to another tab and back, or flip the setting to Light then Dark again.

![Mailpit dark](https://github.com/axllent/mailpit/assets/22807401/383ad9a0-594a-4f6c-b7dd-550fa125b4ce)

**Comment by axllent** [comment]
Thanks for reporting this, it seems to be a Chrome bug where the iframe inherits the background color from the containing page. I'll look into a fix.

**Comment by axllent** [comment]
This should be fixed now in the latest release (v1.9.5). Thanks for reporting the issue :+1:
