### ISSUE TITLE
Request - Wordpres plugin

### ISSUE THREAD

**Issue by KoolPal** [axllent/mailpit#186]
Hi,

This is a request to assist with a plugin just like https://wordpress.org/plugins/wp-mailhog-smtp/

Thanks a lot

**Comment by axllent** [comment]
Mailpit uses the exact same ports as MailHog - doesn't that plugin work with Mailpit too? I do not use WordPress at all, but from what I can see, [all that plugin does](https://plugins.trac.wordpress.org/browser/wp-mailhog-smtp/trunk/mailhog.php) is set the SMTP to use port 1025 on "localhost" (`127.0.0.1`). Assuming it works, then you can either just continue to use that plugin, or alternatively you could create and maintain your own WordPress plugin for Mailpit. Seems simple enough to me (copy/paste/rename) :man_shrugging:
