### ISSUE TITLE
Thank you from fellow developer

### ISSUE THREAD

**Issue by melloware** [axllent/mailpit#187]
@axllent just wanted to say awesome job on Mailpit.  I have been using MailHog for years but have been dissapointed it is abandoned but your tool is actually much better!

I just wanted to let you know I implemented your Docker Container in Quarkus as a Dev service so when Quarkus developers are running locally they can debug their emails before they ship to production.

Quarkus Extension: https://github.com/quarkiverse/quarkus-mailpit

You can close this ticket just wanted to say THANK YOU!

**Comment by axllent** [comment]
@melloware thanks for the kind words and support! It's taken a lot more work than previously planned, but as its popularity grew so did the feature requests 😄

I'm glad to hear you have been able to integrate Mailpit into your development environment, and hopefully you'll get many years of use out of it too!
