### ISSUE TITLE
Allow Mailpit to run at a non-root app context such as /mailpit/

### ISSUE THREAD

**Issue by dforrest-es** [axllent/mailpit#19]
Is there a way to configure an application context? I need to serve Mailpit behind a proxy at `https://{hostname}/mailpit/`. However, the app artifacts (`dist/app.js`, etc) do not include that context.

This behavior would be similar to MailHog's `MH_UI_WEB_PATH` ([docs](https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md))

**Comment by macau23** [comment]
We currently also want to use Mailpit both behind a proxy, and directly.

Previously we used the option `-ui-web-path`, e.g. `-ui-web-path mailpit` to do this, but now this no longer works.

**Comment by axllent** [comment]
I don't understand how your proxy is set up. I use one that that is simply like this which works perfectly fine:

```apache
    <Location "/mail/">
        ProxyPass "http://localhost:8025/"
        ProxyPassReverse "http://localhost:8025/"
    </Location>
```

**Comment by macau23** [comment]
For us, we need to access the application at http://somehost:8025/mailpit/ (i.e. direct) and http://someproxy/mailpit/ so that does not work.

**Comment by axllent** [comment]
I have added a `--webroot` flag for you in v1.2.7

**Comment by dforrest-es** [comment]
Thank you @axllent, and thanks to @macau23 for explaining our similar use cases.

**Comment by saurabhnanda** [comment]
thank you @axllent -- came here looking for this exact use-case.
