### ISSUE TITLE
[BUG] About page does not work behind proxy

### ISSUE THREAD

**Issue by jrod-97** [axllent/mailpit#199]
Hello,

we have deployed mailpit in a restrictive environment and wanted to check which version is deployed.
The about page does not load. I suspect this is because we are behind a proxy and mailpit is not allowed to check for new versions and then can't show about info.
It would be nice to have a timeout in the version check and then just display the current version with a hint:
'There might be a newer version available. The check failed'

Thanks

**Comment by axllent** [comment]
Hi @jrod-97. Thanks for reporting this, and you're absolutely right - I never factored in connectivity issues into the update check web UI. I have added a 5-second timeout which should hopefully work as expected if the connection fails. The modal will also then provide the hint you suggested. 

This will be included in the next release (not sure when but within the next few days). Once released, please feel free to re-open this ticket if you still encounter issues? Thank you.

**Comment by axllent** [comment]
This has now been released with v1.9.10
