### ISSUE TITLE
White screen when visiting the Web UI

### ISSUE THREAD

**Issue by nkosi23** [axllent/mailpit#200]
Hello,

I am new to mailpit and have just installed it using `go install github.com/axllent/mailpit@latest`. While mailpit is apparently successfully launched:

```
me@localhost:~/go/bin> ./mailpit 
INFO[2023/10/29 11:23:11] [smtpd] starting on 0.0.0.0:1025             
INFO[2023/10/29 11:23:11] [http] starting server on http://localhost:8025/ 
```

Visiting the web page gives me a blank page and I can see the following messages in dev tools:

```
Content Security Policy: The page's settings blocked the loading of an inline resource (« script-src »)
 http://localhost:8025/dist/app.css?dev » was blocked due a MIME type (« text/plain ») incorrect (X-Content-Type-Options: nosniff)
 http://localhost:8025/dist/app.js?dev » was blocked due a MIME type (« text/plain ») incorrect (X-Content-Type-Options: nosniff)
```

I apparently get 404 errors for these two files. The HTML of the page is:

```html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0">
	<meta name="referrer" content="no-referrer">
	<meta name="robots" content="noindex, nofollow, noarchive">
	<link rel="icon" href="/favicon.svg">
	<title>Mailpit</title>
	<link rel=stylesheet href="/dist/app.css?dev">
</head>

<body class="h-100">
	<div class="container-fluid h-100 d-flex flex-column" id="app" data-webroot="/">
		<noscript>You require JavaScript to use this app.</noscript>
	</div>

	<script src="/dist/app.js?dev"></script>
</body>

</html>
```

There is nothing fancy in my setup (no reverse proxy etc...) I am just launching the binary.

**Comment by axllent** [comment]
Hi there. You cannot install Mailpit in this way because it doesn't come bundled with precompiled CSS & J's files. Please refer to [the documentation](https://mailpit.axllent.org/docs/install/source/) if you wish to compile it yourself.

**Comment by axllent** [comment]
@nkosi23 Good questions. The pre-compiled binaries do include everything including the "virtual" filesystem used by the web UI (bundled JS, CSS, images etc), but the source code does not include the compiled assets (just the source files to build these). The reason for this is simple: as I'm sure you can image, the precompiled CSS & JavaScript is quite large (relatively speaking). If the compiled versions were bundled and I was to make a small change to either of those, the entire compiled files would be checked back into git each time (not just the line or character change as they are minified, so everything is on a single line). This would lead to a much bigger source repository filled with tonnes of irrelevant historical data.

Anyway, this is the path I chose, and while that does mean that `go install...` doesn't work, I have provided multiple ways to install a fully working version, and instructions for those wanting to compile it (all) from source.

I hope that makes sense?
