### ISSUE TITLE
Feature request: Link Check - allow insecure/selfsigned https:// links to be checked

### ISSUE THREAD

**Issue by wadabum** [axllent/mailpit#204]
My QA-Env. has "real" domains bent back to itself in /etc/hosts, using a self-signed certificate.
- LinkCheck results in "all errors" with `Cannot connect to server` 
- DevTools/API reveals this as `StatusCode: 0, Status: "certificate signed by unknown authority"` in the json-response

As minimal fix, some general "link-check-ignore-https-errors" flag would be nice. (as example [Puppeteer´s "ignoreHTTPSErrors"](https://devdocs.io/puppeteer/#puppeteerconnectoptions))

**The ultimate fix would also allow to directly specify the to-be-allowed-certificate/CA** 
(imagine `--link-check-no-verify [false]|true|/etc/ssl/certs/ssl-cert-snakeoil.pem`) (as example see [Guzzle´s verify options](https://docs.guzzlephp.org/en/stable/request-options.html#verify))

**Comment by wadabum** [comment]
in addition to that I´ve noticed: 
- **HTML screenshots** exhibits the same issue (in `/proxy?url=...` URLs)
 `Get "https://...": tls: failed to verify certificate: x509: certificate signed by unknown authority`

so when adding a flag for allowing link-checker this should be implemented here too,
-> with either the same --arg-switches or one for each I dont know ;-)

**Comment by axllent** [comment]
@wadabum I am really trying to minimize the number of CLI arguments (and environment variables), so I am in favour of a single generic flag, something like `--ignore-tls-errors` which one can optionally apply, and be used for multiple things (including SMTP). I need to give this some thought first as it should be clear what it does (and not confuse users).

**Comment by axllent** [comment]
@wadabum I have added an option for this in [v1.10.0](https://github.com/axllent/mailpit/releases/tag/v1.10.0) (env `MP_ALLOW_UNTRUSTED_TLS` or `--allow-untrusted-tls`). Please confirm this solves your issue?

**Comment by wadabum** [comment]
Working perfectly (for html&linkcheck)
Thank you very much 👌
