### ISSUE TITLE
Allow using privileged (<1024) port for Docker image

### ISSUE THREAD

**Issue by nevergone** [axllent/mailpit#212]
Please Allow using privileged (<1024) TCP port. For example, UI: 80 and SMTP: 25

neccessary:
libpcap and `setcap CAP_NET_BIND_SERVICE=+eip` to binary result

**Comment by axllent** [comment]
Glad to hear it. Mailpit can run with those ports if run as root. There isn't currently any support for running as a non-privileged user below 1024, however if running within docker then this can be easily mapped (or run as root).
