### ISSUE TITLE
How to run mailpit in backgroud ?

### ISSUE THREAD

**Issue by imrostom** [axllent/mailpit#214]
I installed Mailpit on my Ubuntu 20.04 LTS DigitalOcean droplet using a Bash script. Following the installation, I executed the application with "./mailpit", and it functioned correctly. However, I observed that when I closed the terminal, the application stopped working.

**Comment by axllent** [comment]
Hi @imrostom. I'm afraid you will need to be much more specific for me to try give you an answer to this. What operating system are you using, and how did you "install" Mailpit?

**Comment by jure965** [comment]
@imrostom please detail your use case. If you want to run in the background temporarily, you can use [tmux](https://manpages.ubuntu.com/manpages/trusty/man1/tmux.1.html) or [screen](https://linux.die.net/man/1/screen). For more permanent solution with start-at-boot capabilities, you can set up a systemd service around Mailpit.

**Comment by axllent** [comment]
@imrostom Sorry, I did not realise you had edited your original comment as that does not send a notification / alert. It sounds to me like you should simply set up a systemd service to start Mailpit. [Here is a link](https://linuxhandbook.com/create-systemd-services/) (one of many) that explains how to do it. Obviously you will need to modify the service script to suit your Mailpit startup options, and, assuming you are not intending to run it as root, you will have to add those options to the service script too. There are plenty articles on the internet of how to achieve what you are after though, Google will help.

**Comment by imrostom** [comment]
Sorry for the late reply, I solved my issue using **nohup**  command. Thank you @axllent for your instant support.

**Comment by axllent** [comment]
Just for future reference to others, I have added [some documention](https://mailpit.axllent.org/docs/install/systemd-integration/) for auto-starting a native installation (non-docker) of Mailpit on Linux.
