### ISSUE TITLE
Possibility to select multiple tags from the GUI

### ISSUE THREAD

**Issue by PhenX** [axllent/mailpit#216]
Hello, I know it's possible to specify  "tag:XXX" multiple times in the search query, but it would be great to be able to select multiple tags from the GUI.

**Comment by axllent** [comment]
Thanks for the suggestion @PhenX . Do you agree that a Ctrl-click approach on the tags on the left would work here?

**Comment by axllent** [comment]
Like this... (in development, not released yet) - I am clicking the tags while holding down the Ctrl key. Is this what you are asking for?

https://github.com/axllent/mailpit/assets/1463435/9259781c-1aed-44aa-9a18-b95dc8e63318

**Comment by PhenX** [comment]
It looks good to me ! Maybe with a title to know the key for the multiselection. Another alternative would be to add a check box, I don't know.

**Comment by axllent** [comment]
@PhenX This feature has now been released as part of [v1.11.1](https://github.com/axllent/mailpit/releases/tag/v1.11.1). I decided not to add any clutter to the web UI as I try keep the UI as clean as possible, however I have made some notes on this in the online documentation [here](https://mailpit.axllent.org/docs/usage/), [here](https://mailpit.axllent.org/docs/usage/tagging/) and [here](https://mailpit.axllent.org/docs/usage/deleting-messages/).

I'm closing this as complete, however feel free to reopen it if there are any issues.
