### ISSUE TITLE
Caddy example for proxy

### ISSUE THREAD

**Issue by lil5** [axllent/mailpit#232]
As per the documentation see link, I’ll show you how I added mailpit to caddy server. 

Documentation ref: https://mailpit.axllent.org/docs/configuration/proxy/

Example:

`/usr/local/bin/mailpit --smtp 127.0.0.1:8084 --listen 127.0.0.1:8085 --smtp-auth-allow-insecure --smtp-auth-accept-any --webroot /mailpit/`

```caddy
localhost {
	redir /mailpit /mailpit/
	handle_path /mailpit/* {
		rewrite * /mailpit{path}
		reverse_proxy 127.0.0.1:8085
	}
}
```

Original: https://github.com/the-clothing-loop/website/blob/main/devops/templates/Caddyfile

**Comment by axllent** [comment]
Thank you for the information @lil5. Can you please confirm the websocket works too with this configuration (ie: the web UI shows the messages instantly when they are delivered to Mailpit)?

**Comment by lil5** [comment]
Yes the web ui works great 👍

**Comment by axllent** [comment]
I've updated the website instructions :+1: Hartstikke bedankt!
