### ISSUE TITLE
Responses with different SMTP error codes

### ISSUE THREAD

**Issue by DragoMlakar** [axllent/mailpit#235]
It would be convenient for testing that on some conditions response is SMTP error code. 
Maybe some list of email addresses and error codes. Or even on mail content parsing.
Can this be done already and I'm missing something?

**Comment by axllent** [comment]
@DragoMlakar There is currently no way to artificially return an SMTP error code, only if there is an actual error. You could for instance set the `--smtp-max-recipients 3` and provide 4 addresses (which would return an error code).

What exactly are you trying to test here?

**Comment by DragoMlakar** [comment]
Testing how real postfix behave on SMTP errors. Currently if all different NDN bounce mails are DKIM signed. It would be also convenient to test application logic how it handles different SMTP responses.

**Comment by axllent** [comment]
Unfortunately what you are describing is completely out of scope for Mailpit - can you imagine how much work it would be to implement a full postfix "clone" including Non Delivery Reports, DKIM etc? The whole idea of Mailpit it that it accepts everything (provided it is a valid message + SMTP transaction), and then allows you to see what was delivered. Simply put, Mailpit is not postfix.

I have also considered artificial SMTP errors, but this gets really complicated to do it properly. I've seen some solutions that just return random error responses, however it is important that these errors are returned at the correct stage during the SMTP transaction, and again gets very complicated to implement correctly, especially when different SMTP servers return very different error messages for the same things.
 
You may find your solution by delivering your emails directly to an actual postfix server which is then configured to relay messages to Mailpit, but that's about all I can suggest, sorry.

**Comment by DragoMlakar** [comment]
Thnx for feedback. 
Found one that looks promising.
https://medium.com/linagora-engineering/a-mock-smtp-server-for-remote-mail-delivery-testing-2d1a2cfd2798
