### ISSUE TITLE
Subject display mismatch when using | and multiple whitespace characters 

### ISSUE THREAD

**Issue by Tarboy3000** [axllent/mailpit#238]
I've noticed that the subject displayed in the UI is not reflecting the internally saved subject when it contains `|` and multiple successive whitespace. It seems like they get reduced to a single one.
Is this intended/some kind of email display behaviour? The raw tab contains the correct information retaining every whitespace. 

Example subject:
`12345 |   |     | Some text`

**Comment by axllent** [comment]
Thank you for reporting this issue. I have just released v1.13.0 which now displays spaces correctly in message subject (messages list & message summary), and also in the address fields in the message summary.
