### ISSUE TITLE
HTML & HTML Source message tabs are not available in Chrome

### ISSUE THREAD

**Issue by antonkomarev** [axllent/mailpit#24]
What is the reason that HTML & HTML Source tabs are not available in Chrome? Is it a bug, or not implemented yet feature?

Firefox:
<img width="1440" alt="Screenshot 2022-11-22 at 15 39 36" src="https://user-images.githubusercontent.com/1849174/203305286-b81fcce0-259a-4859-98ac-1ae5fc6076d2.png">

Chrome:
![2022-11-22 15 37 06](https://user-images.githubusercontent.com/1849174/203304962-9783840a-8c80-4451-8abb-dcd141f198c4.jpg)

**Comment by antonkomarev** [comment]
It looks like is was an issue with Chrome Extensions.

**Comment by axllent** [comment]
Thanks @antonkomarev, could you please tell me what chrome extention was causing the issue?

**Comment by antonkomarev** [comment]
I'm not sure. One of my team members faced the issue. She disabled all extensions and re-ensbled them. And now it's working.

**Comment by IgnisDa** [comment]
@axllent I get the same problem. I can not see the tabs both in firefox and chrome.

Firefox:
![image](https://user-images.githubusercontent.com/60938164/229171807-b2151584-c2f6-4afb-9826-a7a15b9956b8.png)

Chrome:

![image](https://user-images.githubusercontent.com/60938164/229171903-badc22ac-afdc-424b-bbce-fb65d8fce429.png)


I am using `1.5.1`.
