### ISSUE TITLE
Feature: Case sensitive search, filter by all tags, search API

### ISSUE THREAD

**Issue by Tarboy3000** [axllent/mailpit#240]
For brevity I gathered them all in this issue, but if it's better to split them into separate ones for better searching/tracking let me know. 
1. Is there a reason searches are case insensitive and are there plans to add case sensitive search?
2. How do you filter out emails containing any tag? I played around a bit but something like `!tag` doesn't seem to work, maybe there could be a new filter like `has:tag`?
3. The search endpoint is a 1:1 reflection of the search via UI, a single string containing all filters. It makes sense as there is less complexity involved (since I assume both can simply use the same search functionality in code), but makes the request itself hard to digest if using many search filters when inspected. Would it be possible to have an endpoint that accepts something more akin to an object/multiple parameters instead of a single query string to do complex searches via API? I have to concede though that I don't have much experience designing REST-API myself so I wouldn't know what exact implementation would be a well-designed alternative.

**Comment by axllent** [comment]
>     1. Is there a reason searches are case insensitive and are there plans to add case sensitive search?

I don't know of any search engine which is case sensitive. There are several technical reasons relating to how databases work which I won't get into, but the short answer is there will never be any plans to add this. I can't see why something this be would be necessary in a tool such as Mailpit?

>     2. How do you filter out emails containing any tag? I played around a bit but something like `!tag` doesn't seem to work, maybe there could be a new filter like `has:tag`?

What you're looking for is the `is:tagged` search. I see I had missed this in [the documentation](https://mailpit.axllent.org/docs/usage/search-filters/) so I've added that now. Thanks for pointing that out.

>     3. The search endpoint is a 1:1 reflection of the search via UI, a single string containing all filters. It makes sense as there is less complexity involved (since I assume both can simply use the same search functionality in code), but makes the request itself hard to digest if using many search filters when inspected. Would it be possible to have an endpoint that accepts something more akin to an object/multiple parameters instead of a single query string to do complex searches via API? I have to concede though that I don't have much experience designing REST-API myself so I wouldn't know what exact implementation would be a well-designed alternative.

I don't have enough context here to understand why you are wanting to inspect search queries? Your Github profile is either entirely private or you don't publish any code, so I can't determine your background based on that. Yes you are correct, the web UI uses the API (they are the same), and the search filter parsing in the API is to simplify the search process from the frontend user.

**Comment by Tarboy3000** [comment]
> I don't know of any search engine which is case sensitive. There are several technical reasons relating to how databases work which I won't get into, but the short answer is there will never be any plans to add this. I can't see why something this be would be necessary in a tool such as Mailpit?

I see, thanks for explaining. I wasn't aware there are technical reasons for it. I suppose I was thinking less of the Mailpit search feature as a search engine and more like the usual text search in any IDE that allows you to search with matching case. I assume there are big performance implications searching through a database compared to locally stored files.

> What you're looking for is the `is:tagged` search. I see I had missed this in [the documentation](https://mailpit.axllent.org/docs/usage/search-filters/) so I've added that now. Thanks for pointing that out.

Great to know that it was already implemented, thanks for updating the docs.

> I don't have enough context here to understand why you are wanting to inspect search queries? Your Github profile is either entirely private or you don't publish any code, so I can't determine your background based on that. Yes you are correct, the web UI uses the API (they are the same), and the search filter parsing in the API is to simplify the search process from the frontend user.

That's my bad, I worded myself poorly. What I meant to ask was if it is possible to have a Search Endpoint that uses multiple query parameters instead of a single one. Here is an example of what I mean:

Currently, the following email search filters
- Subject containing "My reply 212" and "My reply 213"
- Sent by "address@example.com"
- Has attachments

are grouped into a single query string:
query: `subject:"My reply 212" subject:"My reply 213" from:"address@example.com" has:attachment`

I would find it easier to work with if it was split into multiple query parameters for each search type instead:
subject: `"My reply 212" "My reply 213"`
from: `"address@example.com"`
hasAttachment: `true`

That way there wouldn't be a need to prefix each term as the search type is determined by the parameter's name.

**Comment by axllent** [comment]
Thanks for the detail @Tarboy3000. To be honest I'm not keen on implementing a separate/different search endpoint without knowing & understanding why exactly. It is far more than just adding a URL, it is also the entire SQL query builder which has to "translate" those queries into various database queries. Having two completely different routes and search logic means I need to maintain these, and every time something is changes in one then it needs to be changed in another place ~ easy to overlook and make a mistake. To put it into perspective, this is the current query builder: https://github.com/axllent/mailpit/blob/develop/internal/storage/search.go#L205-L335

So if this request it is just to make a little bit easier for your particular requirements, please understand that this makes it a lot more difficult for mine. To the best of my understanding, nobody else seems to have any issues with the existing implementation, probably because it aligns with other search engines included in Gmail, Google, Github etc.

I hope that makes sense?

**Comment by Tarboy3000** [comment]
No worries, it was merely a suggestion to build search requests easier programmatically, but I understand that given the already existing endpoint and its syntax parity with the UI, it's a big ask to suggest an alternate one.

Thanks a lot for making Mailpit! It's been a tremendous upgrade from Mailhog, especially given the latter's API.
