### ISSUE TITLE
Feature request: Configuration of logging

### ISSUE THREAD

**Issue by we3geeks** [axllent/mailpit#246]
Consider adding configuration options to have logging go to a file, with the location and name of the file also configurable.

I've used Mailpit through Homebrew and can do this as part of the startup command with redirection of stdout to a file of my choice. I've switched to running Mailpit via Docker with the mail database file on a Docker-mounted volume; I'd like to have the logging output go to a file on that same Docker-mounted volume.

**Comment by axllent** [comment]
Thanks for the suggestion, I am sure this can be added as a new feature. When you say "options" (plural), what options other than a file name are you suggesting? 

In the interim, docker logs can be viewed with `docker logs <container>`, not to mention that you can probably redirect Mailpit logs to a file within docker too simply by adding that to your docker commands.

**Comment by we3geeks** [comment]
Apologies; poor choice of wording on my part. Having _an_ option to specify a file with path (similar to the mail database option) would be sufficient.

**Comment by axllent** [comment]
@we3geeks Awesome, thanks for the clarification - I'll see what I can do :+1:

**Comment by axllent** [comment]
I've added this feature in [v1.13.2](https://github.com/axllent/mailpit/releases/tag/v1.13.2) (using `--log-file <filepath>` or the `MP_LOG_FILE=<filepath>` environment variable). The log formatting is somewhat different to the default stdout logging, but this format makes more sense for a physical logfile. 

Please let me know if this works for you?

**Comment by we3geeks** [comment]
Looks great! Thanks for the quick turnaround on this.

**Comment by axllent** [comment]
Excellent, you're welcome. I'll take that as "it's tested and working" and close this, however feel free to re-open if there is an issue.

**Comment by we3geeks** [comment]
Yes, tested and working as expected.
