### ISSUE TITLE
Allow search filtering of Reply-To header

### ISSUE THREAD

**Issue by marshmn** [axllent/mailpit#247]
It would be helpful to be able to search for emails that match a given `Reply-To` header.

For example, I'd like to be able to use something like the following in the search field: `reply-to:"foo@example.com"`

(In my particular case, I'd like to be able to search on this field using the API `search` endpoint - but I'm assuming that this will be possible once added to the UI search)

**Comment by axllent** [comment]
No problem, I'm looking into this for you.

**Comment by axllent** [comment]
This feature has just been added to v1.13.3, and includes the search filter (`reply-to:<search>`) in the API search and web UI (the web UI uses the API). 

Please note that the ReplyTo field in the [JSON response](https://mailpit.axllent.org/docs/api-v1/view.html#get-/api/v1/search) will be an empty array for any existing data in your database as the `Reply-To` header wasn't indexed previously. If you have existing messages you with to search (by `reply-to:...`) then you will need to reindex your database (`mailpit reindex /path/to/your/db`) which should resolve the issue.

Please confirm this resolves the issue? Thanks.

**Comment by marshmn** [comment]
I've just tested with v1.13.3 and can confirm that it works exactly as I'd hoped - both in the UI and API.

Many thanks for adding this feature so quickly!

**Comment by axllent** [comment]
Perfect, and you are welcome! Thanks for testing.
