### ISSUE TITLE
Nuxt 3 devtools integration

### ISSUE THREAD

**Issue by tdolsen** [axllent/mailpit#248]
Not an issue - just dropping a note to inform about a simple [Nuxt](https://nuxt.com/) 3 module I've put together, integrating the Mailpit web UI in the Nuxt devtools. (In case you feel it could be mentioned somewhere.)

Repository: https://github.com/tdolsen/nuxt-mailpit
NPM package: https://www.npmjs.com/package/nuxt-mailpit

Suggestions welcome.

Looks like this:
![image](https://github.com/axllent/mailpit/assets/180510/afece7e8-33cb-4edb-a823-2dd7a39cf3bf)

**Comment by axllent** [comment]
Thanks. Can you please explain what the purpose of this module is so that people (including myself) can understand what it is used for exactly?

**Comment by tdolsen** [comment]
The purpose is to have easy access to the Mailpit web UI when developing [Nuxt](https://nuxt.com/) applications, in the framework's devtools.

**Comment by axllent** [comment]
Cool. At this stage I'm not going to add list of any related tools just yet, but my suggestion would be to add the `mailpit` topic to your project (see screenshot) - that way it'll be listed in that [topic on GitHub](https://github.com/topics/mailpit). Users also search / view these issues too, so the fact that you have mentioned it here is great too :+1:  I'll close this as it's not really an open issue. Thanks for your input and for using Mailpit!

![Screenshot](https://github.com/axllent/mailpit/assets/1463435/1bf947a5-3514-40a2-9a94-3395858bf610)
