### ISSUE TITLE
404 to api while using webroot

### ISSUE THREAD

**Issue by macau23** [axllent/mailpit#25]
I am launching mailpit with --webroot mailpit but I get a 404 in the UI. The URL returning the 404 is:
`http://somehost:8025/mailpit/api/v1/messages?limit=50`

Without --webroot the URL is:
`http://somehost:8025/api/v1/messages?limit=50`
and this works.

**Comment by macau23** [comment]
Version v1.3.0

**Comment by macau23** [comment]
Works in v1.2.7, seems to have broken in v1.2.8

**Comment by axllent** [comment]
@macau23 Thanks for the bug report. This fix will be included in the next release later today.
