### ISSUE TITLE
Unable to access documentation website

### ISSUE THREAD

**Issue by axelgenus** [axllent/mailpit#250]
I am trying to access the website and the documentation but I receive a message stating that `87% of connections from your network have been flagged as abusive`. Now, "my network" is actually my entire ISP network and I really can't control what other users do. Is it possible to make the documentation available with the source code, on the GH Wiki or somewhere else?

**Comment by axllent** [comment]
In all fairness you weren't actually immediately "blocked", your browser was challenged using an "[invisible reCAPTCHA](https://developers.google.com/recaptcha/docs/invisible)". It would appear your DNS blocking likely prevented your browser from actually doing the challenge successfully, and so it failed the test.

Again, I am really sorry you had this issue, but this is a rather extreme edge-case (you being on a network with such a high reported abuse score AND blocking/hindering the functionality which is there to provide a way through for "humans"). I deal a lot with internet security, and the percentage of malicious website traffic is scary. There is always the risk of some collateral damage (false positives), but at the same time the WAF blocks the vast majority of bad actors before they even hit the websites that sit behind the WAF. The "percentage bad actors" method that blocked you is only one of several tests done per request, per connection, but it does work well as a first line of defence.

I'm glad you managed to find a work-around though ;-)

**Comment by edubacco** [comment]
Same problem here, and I have the ISP "aruba.it".
I can see the doc via my mobile connection or via wayback machine, but I agree with axelgenus that blocking all IP's owned an ISP is too restrictive..
I've been using aruba for about a year now, and I spend online at least 8h / day; this is the first time something like this happens to me.

**Comment by axllent** [comment]
Hi @edubacco. I am sorry to hear you have difficulties accessing the site. The website does sit behind a fairly advanced Web Application Firewall, but like all WAFs, it can at times be a fairly blunt tool especially considering the ever-increasing abusive behavior and growing networks used in targeted attacks. In regards to `aruba.it` (`Aruba S.p.A.`), this is a very abusive network with over 90% of all connections coming from this provider being reported for abusive behavior. 

Unfortunately for you, it appears Aruba both provide hosting services as well as consumer internet (if I understand you correctly?) so you got lumped into a general assumption that anything coming from this network is "evil". 

I have modified the associated firewall rules to be less blunt in future, and it should only block all access from IPs from abusive networks which have been specifically reported. Assuming your IP is one of the IPv6 IPs from this network (the only range that has not been reported) then you should have access again now.
