### ISSUE TITLE
Plus Addressing for tags

### ISSUE THREAD

**Issue by mitchellkellett** [axllent/mailpit#253]
Google, and now Office 365, supports plus addressing. It would be awesome if we could use plus addresses for tags as an alternative option via the header. 

> Append a plus (“+”) sign, with any combination of letters or numbers to follow, after your email address. For example, if your email address was yourusername@gmail.com, you could send mail to yourusername+friends@gmail.com or yourusername+mailinglists@gmail.com and still receive mail at yourusername@gmail.com.

**Comment by axllent** [comment]
That's a great idea, thanks!

**Comment by axllent** [comment]
[Plus addressing](https://mailpit.axllent.org/docs/usage/tagging/#plus-addressing) has now been added to [v1.14.1](https://github.com/axllent/mailpit/releases/tag/v1.14.1). 

I have also added an option (`--tags-title-case` or `MP_TAGS_TITLE_CASE=true`) to automatically TitleCase newly-created tags (manual or automatic) which may be useful here, meaning `user+tag@example.com` would create a tag called `Tag` (not `tag`). This option will not change any existing tags, only new ones.

Please confirm this works as you expect? Thanks.

**Comment by mitchellkellett** [comment]
Hey, sorry I didn't get to test this sooner.

It seems to work fine with one tag
<img width="469" alt="image" src="https://github.com/axllent/mailpit/assets/51467505/df49218f-448c-45a3-9024-19205f3a0aa4">

But not with 2 (I don't know what Google and the likes do if you use multiple plus addresses).
<img width="509" alt="image" src="https://github.com/axllent/mailpit/assets/51467505/d67cf378-1356-4d8c-8ad7-4e68b2f4ca68">

Interestingly, it also applies the logic to the from as well. Not sure if that's intentional. I do like it, though.
<img width="503" alt="image" src="https://github.com/axllent/mailpit/assets/51467505/a819398d-55d6-43ba-9282-0ba7e61d1089">

Title case worked as I expected it to.

**Comment by mitchellkellett** [comment]
My very quick test showed that Google was happy to accept multiple tags, but Outlook only liked one tag (it actually rejected the message when I used two).

> So your expectation is that test+tag1+tag2 would apply both tag1 and tag2? I'm sure that shouldn't be a problem, just not until next week as I'm away for a few days. I'll look into this though.

Following the Google logic, yes, apply both tags.

> I'm also wondering if yes-no-maybe should become yes no maybe ~ as in - replaced with a space. This would only apply to plus addressing as it's not possible to otherwise have tags with spaces. What are your thoughts?

I don't think it should have spaces, I think that you either combine multiple tags to get it or you concat them with hyphens.

**Comment by axllent** [comment]
Are you meaning that `test+tag1+tag2` should tag it as `tag1 tag2` (one tag, two words), or as two separate tags?

**Comment by mitchellkellett** [comment]
Google tags it as two tags, so `tag1` and `tag2`. So I think that's the way to proceed personally.

**Comment by axllent** [comment]
The latest release adds support for adding multiple tags. I'm away for a few days so I haven't tested this as much as I would like to have, but could you please test this and confirm it is working as you expect now? Thanks.

**Comment by mitchellkellett** [comment]
I found a bit of an unusual bug when I have `MP_TAGS_TITLE_CASE=true`. But otherwise, the tags are created correctly when the message is received.

I sent these 6 messages, which all worked fine.
<img width="721" alt="image" src="https://github.com/axllent/mailpit/assets/51467505/ff3f3f94-a792-4fd5-ad2d-bdd15aac722a">

I then went in and read the first one I sent, when I go back to the inbox, they've all be dropped down to lower case.
<img width="720" alt="image" src="https://github.com/axllent/mailpit/assets/51467505/683a4e8e-9343-4e23-8db9-80055a19bacb">

**Comment by axllent** [comment]
Thanks for testing. Title casing only applies to new tags, but you already had the lowercase tags in the database from the previous tests. This is just a "cosmetic issue", not a functional one, so for the purpose of this I'm not worried about it. One day I'll try to find an elegant solution to this without having to query the database twice (set this tag, and then what tags do you actually have) as this would add a lot of unnecessary database queries for every new message.

Cool, I'll close this issue now as I'd say it's working.
