### ISSUE TITLE
API to Identify Missing and Incorrectly Formatted Headers

### ISSUE THREAD

**Issue by skoomer01** [axllent/mailpit#255]
I know Mailpit offers an API that provides email headers, which is incredibly useful. Would it be possible to also have an API that specifically highlights any missing headers and identifies those that are incorrectly formatted? I was thinking it offering a breakdown of missing headers and flagging any headers that do not adhere to standard formatting conventions.
Showing only information like this.
![Untitled](https://github.com/axllent/mailpit/assets/149877250/8f3a3d7c-8138-471f-8095-5bd150fb1ece)

**Comment by axllent** [comment]
Hi @skoomer01. I am a bit confused as both Date and Message-Id are added automatically via the SMTP process, so those would never be missing in Mailpit. Do you have examples of messages in Mailpit where these headers are missing? 

Formatting is a different story though, and I'm really not sure how that could be addressed. Can you please explain in more detail how these messages are being generated, and what happens when you deliver them to Mailpit?

**Comment by skoomer01** [comment]
Hi, sorry for the confusion, I am a junior developer so I might not phrase my questions all that good :).
I am working on a bigger project that doesnt use mailpit yet but they want to implement a way of checking if an email has all the needed headers before sending it, so I asked if there is a plan on implementing an API for that in the future. Since I dont use Mailpit in this project yet I cant provide examples of messages. 
The missing messages are not from Mailpit, I use another web GUI for checking spamminess, I just used that photo as an example of how I thought the response from the API would look like.
Sorry again for the confusion.

**Comment by axllent** [comment]
No problem @skoomer01. I believe that what you are looking for may already be covered using the [SpamAssassin integration](https://mailpit.axllent.org/docs/configuration/spamassassin/) which Mailpit already has, and which appears to be similar to (if not the same) tool you are comparing it to in that screenshot. Please note that the SpamAssassin integration is still somewhat experimental, although appears to work as expected in my testing. There is also an [experimental API endpoint](https://mailpit.axllent.org/docs/api-v1/view.html#get-/api/v1/message/-ID-/sa-check) to test it via an API.

This is not really a "check to see if all headers are correct", as there really isn't a way of doing this accurately (there are just so many headers), but SpamAssassin will probably trigger with common errors. Also to answer your question (as best I can), there are no plans to try validate email headers directly in Mailpit. the SMTP protocol already has checks in place for the most important headers required to send, so my the time Mailpit stores the message it has passed those tests (else it would most likely get rejected by the SMTP server.

I hope this answers your question?
