### ISSUE TITLE
SPF, DKIM, DMARC checking

### ISSUE THREAD

**Issue by DragoMlakar** [axllent/mailpit#261]
Is there any play about checking validity of emails through SPF,DKIM,DMARC?

**Comment by axllent** [comment]
No sorry, I do not currently have any plans to add this. I'm not saying it will never happen, but I believe it would take a fair amount of work to implement properly, and it is likely to cause more issues than that it would solve. Mailpit is intended as a "sending" SMTP, whereas SPF, DKIM & DMARC apply to the "receiving" mail server. I am open to a pull request if you wanted to implement this in a fork though.
