### ISSUE TITLE
Feature request: Messages retention

### ISSUE THREAD

**Issue by kzaitsev** [axllent/mailpit#27]
Hello, thank you for such a good tool. We use mailpit for our staging installations, but sometimes we get a lot of message from staging. This requires wiping the mailpit database to reduce the consumption of disk space. 

It would be great if mailpit got feature like retention policy/retetion time, to delete old messages and prevent the mailpit database bloat.

**Comment by axllent** [comment]
Hi @kzaitsev . Mailpit does have a volume-based retention policy (by default 500 messages). Does this not do what you want?

**Comment by kzaitsev** [comment]
@axllent yes, it should help me with my issue. Thank you so much.
