### ISSUE TITLE
Auto Release for certain domains

### ISSUE THREAD

**Issue by gshep86** [axllent/mailpit#274]
Would it be possible to get a feature to auto release emails for certain domains or addresses?

**Comment by axllent** [comment]
Possibly yes. How are you currently configuring the SMTP relay, via a config or environment variables?

**Comment by gshep86** [comment]
via config

**Comment by axllent** [comment]
I will look into adding this some time in the near future.

**Comment by axllent** [comment]
I have been giving this some thought and a feature like this will potentially introduce complications:

1. Which domains or addresses do you mean - the recipients, the sender, or both?
2. If there is a match of the recipients, do all the other recipients get a copy too, or just those matching the domains specified (this would actually be a regular expression)?

The only way I think this could safely work is if it matches only the recipients (not the sender), and only those matching recipients receive a copy regardless of how many other recipients are included.

Is this what you mean?

**Comment by gshep86** [comment]
We would like to whitelist the recipients. I think the way you described it would work best, where only those matching recipients would receive have the email automatically released. Thanks!

**Comment by axllent** [comment]
I've just released this feature in [v1.17.0](https://github.com/axllent/mailpit/releases/tag/v1.17.0) (see release & website link for a brief explanation). Please let me know if this does what you expect? Thanks.

**Comment by gshep86** [comment]
It's working great, thank you!
