### ISSUE TITLE
Attachment sizes

### ISSUE THREAD

**Issue by attikov** [axllent/mailpit#275]
Is it possible to see the sizes of attachments at first glance?
If yes how? If not, it would be nice to have this feature.
thx

**Comment by axllent** [comment]
Yes, you can see the total size of the entire message including all attachments in the left column, and the individual sizes of each attachment listed in the "Download" menu as seen below:

![Screenshot 2024-04-07 at 07-39-32 Mailpit - localhost](https://github.com/axllent/mailpit/assets/1463435/bd434192-2683-4f97-960d-cd93e0c9d70e)

**Comment by attikov** [comment]
ah, I see, thx
