### ISSUE TITLE
SMTP relay "command: unencrypted connection"

### ISSUE THREAD

**Issue by koushyk** [axllent/mailpit#277]
I'm getting an error on trying to relay, MP_SMTP_RELAY_ALLOW_INSECURE does not help

time="2024/04/15 08:19:55" level=error msg="[smtp] error sending message: error response to AUTH command: unencrypted connection"

vars I'm using

MP_MAX_MESSAGES : 2000
MP_SMTP_RELAY_AUTH : plain
MP_SMTP_RELAY_HOST : postfix-mta.devsvc.svc.cluster.local
MP_SMTP_RELAY_PORT : 25
MP_SMTP_RELAY_PASSWORD : *****
MP_SMTP_RELAY_USERNAME : *****
MP_SMTP_RELAY_ALLOW_INSECURE: true

**Comment by axllent** [comment]
Is your postfix running with StartTLS? If so, did you also set `MP_SMTP_RELAY_STARTTLS=true` ?

**Comment by koushyk** [comment]
I've tried multiple combinations, postfix is not using startts

**Comment by axllent** [comment]
That is very strange. Are you able to connect to that postfix server with any other SMTP client? The insecure setting you added is for when the TLS certificate cannot be validated, but you say your server isn't using TLS. It looks to me though as if your server is actually using TLS.

Please try connect to it using another SMTP client to verify it is connectable, and then report back?

**Comment by axllent** [comment]
Actually, I think you're just missing the `MP_SMTP_RELAY_STARTTLS: false` in your config. Postfix, like all modern SMTPD servers requires StartTLS with authentication enabled, however this can be manually disabled. Mailpit's SMTP relay client will therefore try use StartTLS by default when using authentication...  unless you specifically tell it not to.

Please let me know if that solves it for you?

**Comment by koushyk** [comment]
we are using maildev as a previous solution  and it connects fine, I thought MP_SMTP_RELAY_STARTTLS: false is default.
I will doublecheck everything one more time

**Comment by axllent** [comment]
Sorry, you are correct, the default is false.  I have just done some testing here and am able to replicate the error `[smtp] error sending message: error response to AUTH command: unencrypted connection`. This is an error being returned from the server stating that StartTLS is actually required to use authentication (as I previously suggested), so yes, your server is using StartTLS for authenticated connections, most likely with a self-signed/generated certificate when you installed postfix.
```
MP_SMTP_RELAY_ALLOW_INSECURE: true
MP_SMTP_RELAY_STARTTLS: true
```
The above config should do what you want (it works for me). I can't speak for maildev, but I assume it possibly just upgrades (and ignores the self-signed? certificate) by default.

**Comment by koushyk** [comment]
when I've added 
MP_SMTP_RELAY_ALLOW_INSECURE: true
MP_SMTP_RELAY_STARTTLS: true
I've got 
time="2024/05/08 13:35:55" level=error msg="[smtp] error relaying message: error creating StartTLS config: 502 5.5.1 Error: command not implemented"

maybe its related with https://pkg.go.dev/net/smtp#PlainAuth

**Comment by axllent** [comment]
Can you please `telnet postfix-mta.devsvc.svc.cluster.local 25` and then type `EHLO` and paste the response?

I really cannot tell why or where this is failing in your setup, but I have not encountered this issue anywhere before. It would be ideal if you could provide me with a docker script to start my own postfix server which also fails in the same way so that I can further debug the issue and find the cause and/or a fix.

**Comment by koushyk** [comment]
`250-PIPELINING
250-SIZE 20480000
250-VRFY
250-ETRN
250-AUTH PLAIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING`

I will try to reconfigure postfix

**Comment by koushyk** [comment]
After adding to postfix config:
`smtpd_use_tls = yes
smtpd_tls_cert_file = /etc/pki/tls/certs/public.cert
smtpd_tls_key_file = /etc/pki/tls/private/private.key
smtpd_tls_security_level = may`
emails started to work fine, but I'm sure that it should work without tls anyway
