### ISSUE TITLE
regex case insensitive

### ISSUE THREAD

**Issue by q16marvin** [axllent/mailpit#284]
Hi,

first you make a great job... mailpit is awesome!

2 small things, can we make regex case insensitve?

currently it would only work like this:

MP_SMTP_RELAY_ALLOWED_RECIPIENTS: "@example\\.de$|@EXAMPLE\\.DE$"

and btw  i musst set escape this "\" with "\\"... otherwise docker will not except it :)

Thx!

**Comment by axllent** [comment]
Thanks, I'm glad you like it @q16marvin!

Actually you can set this yourself `MP_SMTP_RELAY_ALLOWED_RECIPIENTS: '(?i)@example\.de$'` (I _think_ a single quote works in a docker-compose file). Regular expressions are a little different in Go - see https://regex101.com/r/JUehoJ/1
