### ISSUE TITLE
log in webgui

### ISSUE THREAD

**Issue by q16marvin** [axllent/mailpit#285]
Hi again,

i think it would be realy helpful to have the full log visible anywhere in gui, because for me its intresting "who" tries to connect to the smpt:

mailpit           | time="2024/04/25 12:39:38" level=warning msg="[smtpd] deny LOGIN login:\"test\" from:113.239.202.119"

but this currently i only see in the shell :)

What do you think about it?

**Comment by axllent** [comment]
Whilst I can understand you for wanting an easy-to-see overview of logs in the web UI, there are some reasons this is also a bad idea. Mailpit is used in many different environments, and exposing the log files via the API (what the web UI uses) can be seen as a security flaw as it exposes those logs to the network too (and more than just who failed to connect to SMTP, but if you set to verbose you'll see a lot more and maybe understand what I mean).

Mailpit is not a monitoring system, those logs (via the shell) are meant as an audit-log to try debug Mailpit issues. Failed SMTP attempts should be handled/reported properly via the application trying to send, not the application receiving :-)

Does this make sense to you?

**Comment by q16marvin** [comment]
yes you are right, so forgot please my idea :)
