### ISSUE TITLE
block loading external sources

### ISSUE THREAD

**Issue by q16marvin** [axllent/mailpit#287]
Hi,

is there a way that html view of a mail dont load "external stuff" like images or css? i dont "realy" understand MP_BLOCK_REMOTE_CSS_AND_FONTS :(

thx!

**Comment by axllent** [comment]
Hi @q16marvin. The `MP_BLOCK_REMOTE_CSS_AND_FONTS` option blocks remote CSS & fonts, but not images -  [see here](https://mailpit.axllent.org/docs/configuration/ui-security-policies/) for more details.

Can you please explain to me what "external stuff" (other than css & fonts) you want to block, and why?
