### ISSUE TITLE
Return queued Message ID similarly to how Mailhog did

### ISSUE THREAD

**Issue by Sn0wCrack** [axllent/mailpit#293]
Previously when using Mailhog the SMTP response would return something similarly to `250 2.0.0 Ok: queued as <message-id>`, however Mailpit does not provide a message ID in the response.

While I understand that returning a Message ID is completely optional in terms of the SMTP spec, however this does seem to be one point of incompatibility between Mailhog and Mailpit.

Currently have some things relying on a Message ID being returned from the SMTP response for log processing.

I had filed an issue upstream previously with smtpd as well to see if a function could be added to return the Message ID as well: https://github.com/mhale/smtpd/issues/38

**Comment by axllent** [comment]
@Sn0wCrack - yes I _think_ that _should_ be possible, provided the functionality gets merged and tagged in a new smtpd release. Until then I can't do anything as that response is generated directly from within smtpd.

**Comment by Sn0wCrack** [comment]
It looks like this was merged in a few hours ago and tagged as v0.8.3

**Comment by axllent** [comment]
No problem, thanks for the heads-up! This has been released in [v1.18.1](https://github.com/axllent/mailpit/releases/tag/v1.18.1).

```
telnet localhost 1025
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 grunty Mailpit ESMTP Service ready
EHLO test.example.com
250-grunty greets test.example.com
250-SIZE 0
250 ENHANCEDSTATUSCODES
MAIL FROM:<test@example.com>
250 2.1.0 Ok
RCPT TO:<user@example.com>
250 2.1.5 Ok
DATA
354 Start mail input; end with <CR><LF>.<CR><LF>
Subject: Test message

This is a test.

.
250 2.0.0 Ok: queued as nVDTjWqiMza2hGULKQw48F
```
Please confirm this is what you were after @Sn0wCrack?

**Comment by Sn0wCrack** [comment]
Awesome, thank you so much for getting that implemented so quickly!

I can confirm this is working great for my use case now, really appreciate it!

**Comment by axllent** [comment]
Glad to help!
