### ISSUE TITLE
[Feature Request] Desktop app

### ISSUE THREAD

**Issue by laserhybiz** [axllent/mailpit#297]
I was wondering if it's possible to release a desktop app version of mailpit. I am not to familiar with the code but I don't think it should be that hard to bundle up the frontend assets into an electron app and include the prebuilt static binary and just run/stop mailpit when the app starts up/shuts down.

Let me know if you need any help with this.

**Comment by axllent** [comment]
Hi @laserhybiz. I think that is a great idea, but I'm personally not willing to undertake this, as an electron app would be a completely stand-alone app/project, and I am more than busy enough with Mailpit and my other projects. But that should not discourage you (or anyone else). If you want to develop and maintain an electron app for Mailpit then by all means, please do! 

I'm sure an electron frontend could act very nicely as a GUI wrapper for a prebuilt Mailpit binary, especially handy for those not wanting to use the CLI directly. There is more than just the basic wrapper though, it would also need a configuration interface to configure Mailpit startup options, including ports, network listening interfaces, database, and probably most of the other options too. I assume it's not hard for someone who already has experience with electron / nodejs.

Is this something you would want to do?

**Comment by laserhybiz** [comment]
@axllent I doubt I'll have the time to build and keep up with this project, and I didn't really expect you to either. I just threw it out here, hoping someone from the community might want to tackle it themselves.

**Comment by trajano** [comment]
I used to use https://github.com/ChangemakerStudios/Papercut-SMTP on my desktop before settling on this one.
