### ISSUE TITLE
deploy to ghcr.io 

### ISSUE THREAD

**Issue by trajano** [axllent/mailpit#302]
Hi can you also add a copy to ghcr.io which does not have rate limits like hub.docker?

**Comment by axllent** [comment]
A copy on [ghcr.io](https://github.com/axllent/mailpit/pkgs/container/mailpit) will be included for **new** releases. At the moment you''ll only find the "edge" build in there (which is currently the same as the latest release), however I don't want to create a new Mailpit release without any actual code changes ~ so you'll have to wait for a tagged release (usually every week or two).

**Comment by axllent** [comment]
@trajano  The latest release can now be found on ghcr.io as well.
