### ISSUE TITLE
Add lable to differ between different instances

### ISSUE THREAD

**Issue by Chris53897** [axllent/mailpit#316]
It would be great to have a label, that is displayed right to the name in the gui.
With this people can see direct, in which instance they are.

Maybe something like `MP_LABEL` or `MP_TITLE`
https://mailpit.axllent.org/docs/install/docker/

**Comment by axllent** [comment]
This is an interesting idea. Next to the logo won't work as there isn't enough space (specifically on mobile), but above the Inbox button probably would work.

For context, could you please explain how you're using Mailpit, specifically why there may be confusion as to which instance it is?

**Comment by Chris53897** [comment]
I have 3 symfony projects running with Mailpit includet locally at the same time.
They run at http://localhost:[PORT]
I can only differ them via the port.
Of course if there are e-mail in the inbox it is a bit easier.

**Comment by axllent** [comment]
Makes sense.... I'll look into this in the coming days :+1:

**Comment by axllent** [comment]
I have added this feature, although this has not been released yet as I just released a new version 2 days ago (so I will wait a few more days so I don't annoy package maintainers... sorry).

The `--label` (or env `MP_LABEL`) will do the following:
- Set a "label" in the web UI above the "Inbox" (and similar buttons in other parts of the website) on the left
- Add the label to the HTML head title (tabs / bookmarks)
- Add the label to both the SMTP and optional POP3 servers

![Screenshot 2024-06-21 at 17-02-03 Mailpit - My server!](https://github.com/axllent/mailpit/assets/1463435/239daa79-e7ab-4b6c-99aa-0c77f393116e)

I'll let you know when this gets released. Can you please tell me if this approach is suitable?

**Comment by Chris53897** [comment]
Thanks

**Comment by axllent** [comment]
This feature has been released in [v1.18.7](https://github.com/axllent/mailpit/releases/tag/v1.18.7). Please feel free to re-open this ticket if you experience any issues, and also please let me know if it solves your issue, thanks.
