### ISSUE TITLE
POP3 server: have option to not delete emails right away

### ISSUE THREAD

**Issue by antonionardella** [axllent/mailpit#317]
Hello again @axllent 

for some debugging I needed to keep the emails in the POP3 server even if the client tells to delete them.

Let me know if it is of interest for you

I added the functionality here:
https://github.com/axllent/mailpit/compare/develop...antonionardella:mailpit:no-delete

And also updated the documentation here:
https://github.com/axllent/mailpit-website/compare/develop...antonionardella:mailpit-website:patch-1

If it is making more of a mess than anything, feel totally free to ignore this issue.

Best,
Antonio

**Comment by axllent** [comment]
HI again @antonionardella. I'm afraid this option would break RFC compliance for the POP3 server. The POP3 client would tell the server to delete the messages, and the server would just ignore it. This means that next time the client connects it believes the messages are new and downloads them again and again etc. 

The POP3 client protocol already has an option **not** to delete (simply by not telling the server to delete) - which is typically the option to "leave messages on server" (or "leave messages on server for X days") found in most mail clients. What am I missing here?

**Comment by antonionardella** [comment]
No worries, I thought about that
The issue is that zammad is deleting messages every 30 seconds, which removed the ability to debug and read texts (if one is not quick enough 🤣)

As of Zammad it depends on the server configuration https://community.zammad.org/t/emails-are-deleted-from-my-inbox-when-using-it-as-channel/4419/2?u=skip
![image](https://github.com/axllent/mailpit/assets/7383572/f3e3f317-0f13-446c-aa5f-f3adab4e3611)

Therefore I added a _debug_ flag on my fork to keep messages anyway, at least for debugging reasons.

No worries at all. Let me close this issue then.

Thank you for your time and availability!
