### ISSUE TITLE
[FeatureREQ] Mailrelay on demand

### ISSUE THREAD

**Issue by plexmaniax** [axllent/mailpit#322]
I may have overlooked something, but it would be nice to have the option of forwarding mails when you need them. If I have understood correctly, I can currently forward all mails or forward certain recipients. 

It would be helpful if I had the option to forward manually in the Mailpit backend.  Without having to keep an allowlist in the config. 

If I have overlooked this function, I am sorry.

Best regards

**Comment by axllent** [comment]
Hi @plexmaniax. Sorry this wasn't clear, but when a relay config is set, the web UI displays a button you can click when viewing a message to manually release (relay) that message.

**Comment by plexmaniax** [comment]
@axllent thanks for reply. 
This is what I was searching for :) 

What a great tool!

**Comment by axllent** [comment]
Thank you :heart:
