### ISSUE TITLE
Option to disable automatic tagging with plus in addresses

### ISSUE THREAD

**Issue by jhartmann123** [axllent/mailpit#323]
When testing, our team members and our customer often use plus-addresses, especially when testing onboarding-workflows and the like. We then have lots of emails with addresses like `myname+1@example.com, myname+2@example.com, myname+test123@example.com`.

Those then get automatically tagged with `1, 2, test123`, which does not make much sense grouping / filtering wise. We already tag our emails explicitly with the `X-Tags`-header, so those additional tags from the plus-addresses just disturb the overview.

It would be great if there was an option to disable the automatic tagging for plus-addresses.

**Comment by axllent** [comment]
Sure, that makes sense to me. Leave this with me and I'll see what I can do in the next few days 👍

**Comment by axllent** [comment]
This feature has been released in [v1.19.0](https://github.com/axllent/mailpit/releases/tag/v1.19.0), and I've added some documentation to support [here](https://mailpit.axllent.org/docs/usage/tagging/#disable-auto-tagging). Please let me know if this works for you, and feel free to re-open if you have any issues. Thanks.

**Comment by jhartmann123** [comment]
This is perfect, thank you!

**Comment by axllent** [comment]
Awesome, thanks for the feedback
