### ISSUE TITLE
There's a way to configure SCP, DKIM and DMARC in Mailpit?

### ISSUE THREAD

**Issue by zJvco** [axllent/mailpit#325]
I'm trying to configurate the SCP, DKIM and DMARC in mailpit, but I didn't find anything helpful about it on documentation. My goal is to use mailpit as a MTA (relay smtp server) only to relay the messages.

**Comment by axllent** [comment]
Hi @zJvco . Whilst Mailpit can relay messages via another SMTP server, Mailpit itself does not deliver messages directly to the individual MX servers to whom the emails are addressed. If you are wanting to add SPF/DMARC/DKIM then you will need to add this functionality to the relay SMTP server (which Mailpit is configured to relay through) as that is the server delivering the messages directly to the individual MX servers configured by their domain names.

So if Mailpit is configured to use a specific postfix server to relay messages, then that postfix server will need to be configured.

**Comment by zJvco** [comment]
Hi!

In that case, Mailpit can't send e-mails to mail providers like Gmail or Outlook?

My Scenario is: I have one application (in one AWS EC2) that connects to Mailpit (which is in other AWS EC2) to relay e-mail to providers like Gmail.

relay smtp file:

host:               mail.example.com.br
port:               25
starttls:           true
allow-insecure:     false
auth:               login
username:           test
password:           test
secret:
return-path:
allowed-recipients:

It works?

**Comment by axllent** [comment]
Mailpit will "resend" (route) your email via `mail.example.com.br` - and it is `mail.example.com.br` that then delivers the messages to providers like Gmail & Outlook, not Mailpit. If you need SPF etc, then this needs to be configured on `mail.example.com.br`. Does that make sense?

**Comment by zJvco** [comment]
So it should be:

My application (EC2) > SMTP Server (Mailpit) > Postfix (SMTP Relay)?

That's right?

**Comment by axllent** [comment]
Exactly 👍
