### ISSUE TITLE
Mailpit SSL Support

### ISSUE THREAD

**Issue by eafarooqi** [axllent/mailpit#329]
hi, 

Does mailpit support ssl implementation? I am unable to find any documentation for this. Mailpit works fine with http but with https its not working. Certificates are properly implemented on the server. 

Thanks

**Comment by axllent** [comment]
Hi @eafarooqi . If you're referring to TSL (HTTPS), have you read https://mailpit.axllent.org/docs/configuration/http/ ? Definitely supported in Mailpit.
