### ISSUE TITLE
Firefox on Fedora 39 doesn't show any data for tabs other than HTML

### ISSUE THREAD

**Issue by tmulle** [axllent/mailpit#330]
When I try to look at the other tabs: `RAW`, `HTML Source`, `Headers`, etc. nothing is displayed when using Firefox on Fedora 39.

The only tab that works is the initial `HTML` tab.

When I use Chrome all the tabs work.

`Firefox 127.0.2` for Fedora is the version we are using.

**Comment by melloware** [comment]
Just to add some info @tmulle and I have tested a bunch of combinations Windows, Chrome, Firefox and this seems to be the one browser with an issue that we have found.

**Comment by melloware** [comment]
After further testing it seems to be related to being embedded in the Quarkus DevUI Window:

![image](https://github.com/axllent/mailpit/assets/4399574/40bf8b2f-bf20-4718-b7a8-53c066fd2892)

it works if we open Mailpit in its own tab.  So this might not be a Mailpit issue but a Quarkus Dev UI issue.

**Comment by melloware** [comment]
As a note the MailPit UI is loaded like this.

```xlm
<object width="100%" height="100%" type="text/html" data="http://localhost:63347">
</object>
```

**Comment by axllent** [comment]
Hi guys. My first question would be: what do the Firefox developer tools report (errors)? That's the first place to start as it usually provides a strong clue where things are going wrong.

**Comment by tmulle** [comment]
No errors in the Web Developer console just warnings when run in the Dev UI and no errors on the Network tab when clicking tabs.

<img width="3000" alt="Screenshot 2024-07-05 at 5 17 30 PM" src="https://github.com/axllent/mailpit/assets/5183186/bb23779c-e0e3-48c3-86e5-2f2aaa93efb0">

**Comment by melloware** [comment]
Yep we think it's specifically Fedora and Firefox. Ubuntu seems to be ok. And yes the app works fine if it's opened not inside a frame

**Comment by axllent** [comment]
> Yep we think it's specifically Fedora and Firefox. Ubuntu seems to be ok. And yes the app works fine if it's opened not inside a frame

Thanks for the confirmation. It _sounds_ very, very specific, a needle in a haystack - a specific version (?) of Firefox on a specific platform, only whilst viewing Mailpit via Quarkus. I wonder if it's some Red Hat specific security patch they apply to Firefox which affects functionality within an object?

I think there is potentially still merit in testing points 2 & 3. Another good test that would be good is creating a standalone html file with just `<object width="100%" height="100%" type="text/html" data="http://localhost:63347"></object>`  and opening that with Firefox - ie: does that work. That would tell us if it is some restriction to `<objects>` (if it doesn't work), and whether is has something to do with the Quarkus UI (if it does work as expected).

Either way, I don't think there is anything I can do to Mailpit to fix it as it doesn't appear to have anything to do with Mailpit itself.

**Comment by melloware** [comment]
I agree with you. Not a Mailpit issue.

**Comment by axllent** [comment]
Thanks @melloware. Just for the record, I installed Fedora today in a VM and tried Firefox with just a blank page with `<object width="100%" height="100%" type="text/html" data="http://localhost:8025"></object>` - it worked as expected. It definitely seems related to Quarkus.

I will close this issue for now, but please feel free to reopen or comment if the problem has been identified, and if it is something relating to Mailpit - or which Mailpit can potentially change to help work around the problem.

**Comment by melloware** [comment]
Thank you and thanks again for your wonderful work.

**Comment by melloware** [comment]
@axllent we did a Youtube Podcast on Mailpit in Quarkus this morning thought you might be interested: https://www.youtube.com/watch?v=bJMoRPCzc14

**Comment by axllent** [comment]
That's really awesome, thanks for the really positive feedback and for sharing the link with me @melloware! Very slick to see how you've integrated Mailpit into Quarkus... 

Just for reference, the HTML check you were looking at in the video is [documented here](https://mailpit.axllent.org/docs/usage/html-check/) - basically it uses the "database" (a huge set of "rules" & supported platforms defined in JSON format) from caniemail.com to run those tests **locally** to see what elements / styles are problematic on various platforms / programs, and thus your overall score. You were getting 100% because your HTML was very simple and everything you had was supported, so it did not matter what you ticked or not, it was still 100% :) That will change drastically when you start to use CSS flex alignment, floats, background images, remote CSS, HTML5 etc....

**Comment by melloware** [comment]
That is good to know!
