### ISSUE TITLE
Relay recipient blocklist

### ISSUE THREAD

**Issue by zmweske** [axllent/mailpit#333]
First off, I love this application and thank you for creating and maintaining it. 

Would you consider creating a blocklist as well? I think that one simple reason for this would be to block all emails sent to [admin@admin.lan](mailto:admin@admin.lan) for some services so they don't spam a downstream SMTP provider (and prevent spam filtering).

Similar to the allowlist defined by `--smtp-relay-matching`, the blocklist would (in the same but opposite way- list below copied from https://github.com/axllent/mailpit/issues/108#issuecomment-1535317838):
- auto-forwarding silents drops addresses on the blocklist (logged in debug), and sending all other matching addresses (if any). A disallowed address should not block any others from being sent.
- API / frontend will not allow any sending the address list contains invalid addresses, and return an error if any addresses are not allowed
- Frontend would ideally warn beforehand when entering the address

Haven't had time to set up a dev environment yet, but based on #108, it should be very similar with just the inverse logic and an extra branch for the config flag?

Thanks again for your work with this project!

**Comment by axllent** [comment]
Thank you for opening a new issue @zmweske. I will look into this in the near future and see what I can do.

**Comment by axllent** [comment]
@zmweske I have added this feature in [v1.19.1](https://github.com/axllent/mailpit/releases/tag/v1.19.1) and is [documented here](https://mailpit.axllent.org/docs/configuration/smtp-relay/). 

Please let me know if this works as you expected?

**Comment by axllent** [comment]
I'm closing this issue as it was released a week ago. Please feel free to re-open if there are issues.

**Comment by zmweske** [comment]
Had been busy but finally got around to testing it out- works like a charm- thanks so much!

**Comment by axllent** [comment]
Great, thanks for the feedback!
