### ISSUE TITLE
Delete ALL sometimes shows 0 messages to delete even though the inbox has messages

### ISSUE THREAD

**Issue by tmulle** [axllent/mailpit#334]
This is a very minor thing, but when you load the page and watch the inbox fill up with emails and don't click anything on the page other than the `Delete All` button, it will say "0 messages will be deleted"

I've tested this in the standalone window and the Quarkus Dev UI embedded view mode.

This is on Fedora with Firefox and Chrome.. haven't tested with anything else at the moment.

![image](https://github.com/user-attachments/assets/42b7228f-26a7-4d7f-938b-4bda2e074a8e)

**Comment by axllent** [comment]
@tmulle Good catch! Currently that total is set when the inbox view is loaded, but not updated when new messages arrive. It was using the same logic as filtered views (searches / tags) which do not automatically update when new messages arrive.

I've pushed [a fix](https://github.com/axllent/mailpit/commit/21a6f798d1b362c3f788dafbf6a3d6490ed38f7e) for this, but won't won't release a new version just yet ~ I try stagger the releases by a week unless it's a critical fix as not to annoy package maintainers by releasing every other day ;-)

Thanks for reporting!

**Comment by melloware** [comment]
Thanks for the quick fix @axllent !

**Comment by axllent** [comment]
@melloware This has now been released in [v1.19.2](https://github.com/axllent/mailpit/releases/tag/v1.19.2). Please can you confirm this fixes the issue for you, thanks!

**Comment by melloware** [comment]
Thank you @axllent it works. Safe to close ticket!
