### ISSUE TITLE
Amazon ECR Public Gallery

### ISSUE THREAD

**Issue by xiangweilee** [axllent/mailpit#335]
Is it possible to make this image available in [Amazon ECR Public Gallery](https://gallery.ecr.aws/)

**Comment by axllent** [comment]
@xiangweilee Can you please explain to me what the advantage is of having a docker image on ECR? It is already on Docker hub & Github's registry.

**Comment by remram44** [comment]
If it's on GitHub container registry, perhaps you could link it to the repo?

That would make it appear like this on the GitHub page:

![screenshot](https://github.com/user-attachments/assets/5becaafb-d3fc-405b-819b-67dc62ea609f)

**Comment by axllent** [comment]
Thanks for your feedback @remram44. This is actually referenced to on [the website](https://mailpit.axllent.org/docs/install/docker/) as an _alternative_ "[mirror copy](https://github.com/axllent/mailpit/pkgs/container/mailpit)", however I intentionally left it off the GitHub project page as I see Docker Hub as being the primary source for Docker images. Do you see as being a problem for users?

**Comment by remram44** [comment]
DockerHub's rate-limit is a concern, I work in a big university with few shared outgoing IPs. Authenticating pulls using a DockerHub account is possible (for now) but adds complexity.

In addition I feel like the ghcr images makes ownership more obvious (images are built from this repo's source by this repo's CI).

In the end you're right that it wasn't too difficult to find the ghcr images when I was actively looking for them, so your call.

**Comment by axllent** [comment]
I understand your reasoning, and I agree that nobody should have to go through those hoops in a situation like yours.

> In addition I feel like the ghcr images makes ownership more obvious (images are built from this repo's source by this repo's CI).

I think it should be quite clear that those images on Docker Hub belong to this repo as they are both namespaced the same, and are linked to from both the README and the Mailpit website (not to mention the [download stats](https://hub.docker.com/search?q=mailpit) vs: any of the other Mailpit forks).

> In the end you're right that it wasn't too difficult to find the ghcr images when I was actively looking for them, so your call.

That was pretty much my intention - for those that really want / need them they are there, but I don't want to actively drive users to use GH unless they have to. The thing that really annoys me about GH is that they don't actually provide any API methods to obtain registry download statistics, so monitoring daily downloads programmatically is just not an option :-/
