### ISSUE TITLE
mailpit.png 404 page not found

### ISSUE THREAD

**Issue by LiamKarlMitchell** [axllent/mailpit#34]
When an email is received whilst MailPit browser tab is open.
I get an error in network console.

mailpit.svg does exist

![image](https://user-images.githubusercontent.com/1968109/217511515-f7590601-989b-45e1-8386-58dec29f172e.png)

**Comment by axllent** [comment]
Thanks for reporting this @LiamKarlMitchell - I'll fix this shortly and release a new version.

**Comment by LiamKarlMitchell** [comment]
Thankies :) I'm using the http requests from postman to get Registration email link in some testing very neat thanks!
