### ISSUE TITLE
Tags from headers don't respect RFC 2047 encoding

### ISSUE THREAD

**Issue by ScopeyNZ** [axllent/mailpit#344]
If you send a UTF-8 (for example) encoded header value for `X-Tags` then the tag you get will include the encoding artifacts:

![image](https://github.com/user-attachments/assets/28fffb95-09b4-45c8-96f9-158d02bf4fed)
![image](https://github.com/user-attachments/assets/4db0ce9d-48fb-4b70-ac9d-c8342d09721f)

**Comment by axllent** [comment]
I'm not sure why anyone would UFT8-encode the `X-Tags` values when UTF8 characters [are not supported](https://mailpit.axllent.org/docs/usage/tagging/#allowed-tag-names)? Can you please explain the reasoning for UFT8-encoding them in the first place?

**Comment by ScopeyNZ** [comment]
UTF-8 encoding is just a side effect of the mailing service we use requiring other headers to be UTF-8 encoded. You're right that we can work around this on our end by specifically not encoding this header, but I assumed that it might be of interest to have this report here as a record (and I also hoped that it would be somewhat trivial to address 😅).

**Comment by axllent** [comment]
Ahh, I see your point. I'll look into this and see what, if anything, be done about it :+1:

**Comment by axllent** [comment]
This has feature been released as part of [v1.20.1](https://github.com/axllent/mailpit/releases/tag/v1.20.1). It should correctly decode a mime-encoded X-Tag header now, even if that means stripping them of non-supported characters (assuming it contained that). Please let me know if this resolves your issue?
