### ISSUE TITLE
show icon attachment in new side navigation message listing

### ISSUE THREAD

**Issue by rogerdz** [axllent/mailpit#345]
Can you add icon attachment in new side navigation message listing ? 
![image](https://github.com/user-attachments/assets/35997c2f-8b17-4bca-b336-eb835d3889cd)
![image](https://github.com/user-attachments/assets/4921f4c9-8f8b-4418-81a9-b3ac71ab77e7)

**Comment by axllent** [comment]
Yes, I can't believe I completely overlooked that! Something like this?:

![Mailpit](https://github.com/user-attachments/assets/1a5a3b36-0353-4201-ad38-045692ccf57a)

**Comment by rogerdz** [comment]
Sound good

**Comment by axllent** [comment]
This has feature been released as part of [v1.20.1](https://github.com/axllent/mailpit/releases/tag/v1.20.1)
