### ISSUE TITLE
Deploying in heroku containers

### ISSUE THREAD

**Issue by rameshelamathi** [axllent/mailpit#346]
Does anyone had success in deploying the app using Heroku container registry ? 
Any pointers would be really appreciated.

Thanks

**Comment by axllent** [comment]
I have literally zero experience with Heroku, but what I can see on https://devcenter.heroku.com/articles/container-registry-and-runtime it does seem somewhat complicated. My initial thoughts are that you would:
- Pull the official Mailpit docker image (`docker pull axllent/mailpit`)
- [Tag that image](https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-an-existing-image) using the Heroku naming convention (?)
- [Release](https://devcenter.heroku.com/articles/container-registry-and-runtime#releasing-an-image) (?) that image via the Heroku ALI

Not sure about configuring open ports etc..... sorry I can't help more unfortunately. Maybe someone else with experience with Heroku can provide more guidance.
