### ISSUE TITLE
Resize display view size 

### ISSUE THREAD

**Issue by rogerdz** [axllent/mailpit#349]
Mailpit only has 3 option 
![image](https://github.com/user-attachments/assets/5f699e18-db9f-45ab-9cde-5a2cba3e556c)

Can I change display view size by drag and drop?
It is useful in case I want to test the email display at some specific sizes

**Comment by axllent** [comment]
What sizes are you wanting to test, and (assuming it's mobile) can't you just resize your browser width to what you want to test?

**Comment by axllent** [comment]
Great! I realise that it would be nice to have a drag-and-drop width for that, however that functionality would also need to be mobile friendly (work with touch screens on tablets, phones etc), which makes it really complicated to implement and maintain. Having a long list preset sizes always means someone else will want something a little different. The easiest solution (for the smaller sizes like phones) is to just resize your desktop browser to the width you need :+1: Event than it's not 100% accurate, but it gives you a fairly good idea.
