### ISSUE TITLE
Link Check: localhost links not detected

### ISSUE THREAD

**Issue by dregad** [axllent/mailpit#357]
Hello @axllent,

I was testing the LinkCheck feature, and noticed that *localhost* links (which I frequently use while developing) are not detected (http://127.0.0.1 works).

```
php > mail('test@localhost','Test plain link','http://localhost');
```

![image](https://github.com/user-attachments/assets/3733dbac-69dc-41e6-99f4-e6e717182ccd)
![image](https://github.com/user-attachments/assets/52165505-c419-449b-b5db-a8347d283c01)

I guess this could be fixed with a small adjustment to the Regex. e.g. appending `|localhost` at the end of the 2nd capturing group.
https://github.com/axllent/mailpit/blob/dc1a16ed5c065486b5edd24623489b935c7ed4d3/internal/linkcheck/main.go#L13

PS: many thanks for MailPit, it's awesome ❤️

**Comment by dregad** [comment]
Sorry, forgot to mention this is with v1.18.3. I realize it's somewhat out of date, but I can't upgrade just now. I'll test again later with the latest version.

**Comment by dregad** [comment]
Same behavior confirmed with v1.20.3.

**Comment by axllent** [comment]
Hi @dregad - I can confirm your issue - the frontend JavaScript was far more relaxed in how it detected a "valid" URL vs: the "backend" for link checking. I have just pushed a fix and released it as part of [v1.20.4](https://github.com/axllent/mailpit/releases/tag/v1.20.4). Please confirm this new release fixes the issue for you?

**Comment by dregad** [comment]
Thanks for responding so quickly. I think your guy should do the trick, will test and confirm later today!

**Comment by dregad** [comment]
Confirmed working OK in 1.20.4, thank you very much ! 🚀
