### ISSUE TITLE
Incorrect version displayed

### ISSUE THREAD

**Issue by N6REJ** [axllent/mailpit#359]
When I open mailpit and check "version" with "about" I get 1.20.3 instead of 1.20.4
![image](https://github.com/user-attachments/assets/a2761b50-cdef-465f-8204-a8013ae5c669)

**Comment by axllent** [comment]
Then you are actually running v1.20.3 and not v1.20.4 :-) I don't know what else to tell you as you haven't provided any information as to how it is installed, nor how you updated it (assuming you did).

**Comment by N6REJ** [comment]
it's installed as a module on our software https://github.com/Bearsampp/module-mailpit ( http://bearsampp.com ) 
1.20.3 works fine, its only 1.20.4 that doesn't.
if I try to run it manually it says to run from cmd and then closes

**Comment by N6REJ** [comment]
nvm.. its an us issue... fresh download and manual test shows 1.20.4

**Comment by axllent** [comment]
All good, I'm glad you managed to solve it 😎
