### ISSUE TITLE
If External Relay is down, are emails still queued to send/retry?

### ISSUE THREAD

**Issue by dennisjbr** [axllent/mailpit#380]
Hello!
More of a question than an issue to file.  It's unclear if Mailpit is set to relay all messages to another server, and that server is down, will it retry to to send that message later?  Is the status of the send persistent in the database?

Thanks!

**Comment by axllent** [comment]
Hi @dennisjbr. To answer your question, no, there is no queue / retry logic built into Mailpit for relaying messages as this is ultimately completely out of scope for the purpose of the software. There is also no sent status stored in the database - when a message is received Mailpit will attempt to relay the message immediately. If it fails to "auto relay" then the failure is just logged as a failure to the server console.
