### ISSUE TITLE
标题和邮件正文为中文时都是乱码

### ISSUE THREAD

**Issue by tqangxl** [axllent/mailpit#389]
标题和邮件正文为中文时都是乱码
Subject  =?us-ascii?Q?Oracle=3F=3F=3F=3F=3F=3F=3F=3F=3F=3F?=

UTF-8? gbk？
![image](https://github.com/user-attachments/assets/9c670ef5-8fb7-4e09-9117-17d505e55f98)
附件能不能在下载的旁边加个查看的选项，不用下载直接浏览器查看所点击的附件

**Comment by axllent** [comment]
I am sorry but I don't speak or understand Chinese. Based on Google translate however you have two questions:

1. Is your email & subject properly encoded (UTF8 / base64)? `=?us-ascii?Q?Oracle=3F=3F=3F=3F=3F=3F=3F=3F=3F=3F?=` is the same as `Oracle???????????` so I do not understand what you expect. Does this work in any other email client correctly? It is my understanding that you will need to use UTF-8. Maybe you could take a look at https://dencode.com/string/quoted-printable to test.
2. Your browser can only open the file formats it supports - if the browser does not support the format (eg: .man) then it will try download the file instead. Mailpit does not convert attachment formats into something your browser can understand (there are literally thousands of file formats).

**Comment by szsyzx** [comment]
> 标题和邮件正文为中文时都是乱码 Subject =?us-ascii?Q?Oracle=3F=3F=3F=3F=3F=3F=3F=3F=3F=3F?=主题 =？us-ascii？ Q? 神谕者=3F=3F=3F=3F=3F=3F=3F=3F=3F=3F？=
> 
> UTF-8? gbk？ UTF-8 格式？gbk？ ![image](https://private-user-images.githubusercontent.com/9669944/387128589-9c670ef5-8fb7-4e09-9117-17d505e55f98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMzYxNzYsIm5iZiI6MTczMjIzNTg3NiwicGF0aCI6Ii85NjY5OTQ0LzM4NzEyODU4OS05YzY3MGVmNS04ZmI3LTRlMDktOTExNy0xN2Q1MDVlNTVmOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjJUMDAzNzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M5NWNmNmJiZmFmNzk3NDY2NjExNWFkMmYzYWNkYjkwMTk1NzdkZWNlNzNkM2MxNzM0NWE5Yjc1NzQzMjU2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IyMJsu-jxJPxFIxZGxjIEBRHWXnVMKx8TJ94eMsPsIA) 附件能不能在下载的旁边加个查看的选项，不用下载直接浏览器查看所点击的附件

兄弟你是怎么搭建的呢，是在linux下还是
