### ISSUE TITLE
Tray

### ISSUE THREAD

**Issue by trymeouteh** [axllent/mailpit#39]
Please add a tray item in the system tray to easily start and stop the service.

**Comment by axllent** [comment]
Hi @trymeouteh . Mailpit is a developer-orientated tool used for integration testing and testing, and not a desktop UI utility like Syncthing. Adding a multi-platform tray is not an easy task at all, as Mac, Windows and the various Linux GUIs all differ significantly. Adding this, including features such as a Windows or Flatpak installers also includes various additional platform-specific extras and requirements for c-binding to be included (and maintained) in the core library, all adding significant binary size, cross compiling rendering the static binaries useless. The short answer is this will not be added.

The same answer applies to your other feature requests: #36, #37 and #38.
