### ISSUE TITLE
[FeatureREQ] Forwarding Mails without SMTP

### ISSUE THREAD

**Issue by plexmaniax** [axllent/mailpit#390]
Hi it's me again ;)

I'm not sure if I missed this information, but I couldn't find a solution for forwarding testmails without providing any smtp details. We often use sendmail on our server, but we wanna forward the testmails. Is there any way to do this without an external smtp relay?

Best regards

Maik

**Comment by axllent** [comment]
Hi :) No, this is not supported, you have to configure a relay SMTP server. Just to clarify, this also won't be supported in the future due to the technical requirements of a SMTP servers (it's not simple, and completely out of scope of what Mailpit is). Sorry.

**Comment by plexmaniax** [comment]
Thanks for your reply.

sadly to hear, but understanding. I'll try to set a free account on service like mailgun, this will fix my issue.

stay tuned!

best regards
Maik
