### ISSUE TITLE
How to run it under Linux

### ISSUE THREAD

**Issue by szsyzx** [axllent/mailpit#392]
Install via bash script (Linux & Mac)
Linux & Mac users can install it directly to /usr/local/bin/mailpit with:

sudo bash < <(curl -sL https://raw.githubusercontent.com/axllent/mailpit/develop/install.sh)

I've installed via this method, but I don't know how to run it

**Comment by axllent** [comment]
To run mailpit without any options you then just type `mailpit` on the command line (and hit enter). To see a list of options, run `mailpit -h`.

**Comment by szsyzx** [comment]
Thanks for the answer, I run ./mailpit and I can open the web interface normally, but I don't know how to send an email。

**Comment by axllent** [comment]
I am not sure you understand what Mailpit is used for. Mailpit is not used for creating or sending emails, it is used to receive emails. Emails should be sent directly to Mailpit, and Mailpit will accept those emails and display them in the web interface. This is used to test whether the emails work, the contents of those emails are correct, etc. There is more information on how to set up an application to send emails to Mailpit on [the website](https://mailpit.axllent.org/). I hope this helps you.

**Comment by szsyzx** [comment]
What do I mean by this established email service, how to receive email, and what is its address? Where do I need to set it up? Boss, do you have a live chat tool? Let's consult!
