### ISSUE TITLE
Feature: Automatically delete messages by age

### ISSUE THREAD

**Issue by avesst** [axllent/mailpit#393]
Hi,

Thanks for making this, excellent software! 

I feel like it's missing the functionality of being able to specify a max age of a message. For instance, in my use case I would like to be able to have it to automatically delete messages that are older than 24 hours.

**Comment by avesst** [comment]
Sorry. I only read the "Deleting messages" under "Usage" in the docs. Just found the `--max-age` runtime arg.

**Comment by axllent** [comment]
No problem, I'm glad to hear you else find this feature useful :+1: I think the documentation could be improved in many ways, but it's not easy when there are so many features.

**Comment by avesst** [comment]
Perfect!
