### ISSUE TITLE
Change ports?

### ISSUE THREAD

**Issue by trymeouteh** [axllent/mailpit#40]
Is there a way to change the port numbers for SMTP and the HTTP server?

**Comment by axllent** [comment]
Yes there is, eg `mailpit --smtp 0.0.0.0:1025 --listen 0.0.0.0:8025` (those are the default values, but you can change them). Please note that if you are running it as a non-root user then you cannot listen on ports lower than 1024 on Linux/Mac (I don't know about Windows). 

Please see https://github.com/axllent/mailpit/wiki/Runtime-options
