### ISSUE TITLE
Tagging filters with regex support

### ISSUE THREAD

**Issue by stefankluempers** [axllent/mailpit#410]
We use a central Mailpit instance to support various projects. Each project uses a project-specific mail domain. 
It would be very helpful if automatic tagging based on the mail domain could be configured. Can the filter definition be extended to include regex support with matching groups for tag definition?

To use the local part or mail domain for tag definition, the configuration could be as follows, for example:
filters:
```
  - match: addressed:(.*)@example.com
    tags: Tag $1
  - match: from:from@(.*).com
    tags: Tag $1, $1
```

**Comment by axllent** [comment]
Hi @stefankluempers. No, unfortunately this is not possible. The tag matches are ultimately mapped to internal SQL queries, so regex is not supported.

As a suggestion, you could configure your projects to add an  [X-Tags header](https://mailpit.axllent.org/docs/usage/tagging/#x-tags-header) to the emails they send.

**Comment by stefankluempers** [comment]
Hi Ralph, thanks for your quick response. X-Tags headers seam to be a good alternative to my suggestion.
