### ISSUE TITLE
Add EXPOSE to Dockerfile

### ISSUE THREAD

**Issue by mdharm** [axllent/mailpit#63]
Some CI environments look for the list of ports exposed by a container as a way of doing a basic "health check" to verify that the container is running and ready to accept requests.  GitLab is one such CI environment.  Without an EXPOSE statement in the Dockerfile, the gitlab-runner has no way of checking if the mailpit container is ready to operate as a service or if more time is needed.  An error is logged in this case, although it doesn't really affect operation (at least in my tests).

Simply adding the line `EXPOSE 1025 8025` to `Dockerfile` resolves the issue.  If a different set of ports is used (i.e. via `--smtp` or `--listen`` command-line options, then this would require changing the Dockerfile.  But I see this as unlikely for a CI environment, as ports can be re-mapped between containers.

**Comment by axllent** [comment]
@mdharm Thank you, you're absolutely right. I hadn't considered that as I always set the ports manually (tot he same), but these should be open by default in the Dockerfile. This will be included in the next release.

**Comment by axllent** [comment]
This has been included in the v.1.3.11 release. Thank you for your contribution, and please let me know if you have any issues.
