### ISSUE TITLE
Invalid chars in webroot too strict

### ISSUE THREAD

**Issue by adepretis** [axllent/mailpit#64]
I think the invalid char list for the webroot is a bit too strict. Currently only `[^0-9a-zA-Z\/-]` is supported but I think there should be at least `_` allowed too.

For example when hooking Mailhog into an "internal path" that has special access rights, even in non-production environments. For example https://my.service/_internal/mailpit.

Would it be possible to add at least `_` to the list of allowed chars? Maybe also `.` would make sense - think https://my.service/internal.mailpit

**Comment by axllent** [comment]
@adepretis Thank you for raising this - adding those characters is not a problem at all. Both `_` and `.` characters will be included in the next release.

**Comment by axllent** [comment]
This has been included in the v.1.3.11 release. Thank you for your contribution.
