### ISSUE TITLE
[Feature request] Display "Reply-To"

### ISSUE THREAD

**Issue by marcinkunert** [axllent/mailpit#66]
Hey! Thanks for this awesome tool. I would as if you could add the "Reply-To" header to the fields displayed on top of the message?

**Comment by axllent** [comment]
I'm surprised I never noticed that before, thank you for raising it! Yes definitely, Mailpit should display this (which it doesn't... yet). I will leave this ticket open as I have a few other things to finish up first before I can implement this, so it may take a little while.

**Comment by axllent** [comment]
I have just added this feature in v1.5.2. Please try it and confirm it works for you as expected, thanks.

**Comment by axllent** [comment]
I'm closing this issue as it has been three weeks since this feature was added.
