### ISSUE TITLE
[Feature request] Download HTML file

### ISSUE THREAD

**Issue by nztim** [axllent/mailpit#67]
I've found Mailhog to be invaluable and I'm very glad this project exists, thanks for your efforts :)

One task I often perform is to test an email and then provide the design with sample content for others to review. To help with this I sometimes use a screenshot or copy/paste the HTML from the relevant tab but it would be great to be able to simply download an .html file.

**Comment by axllent** [comment]
I'm sure I could add a few more download options such as downloading the email HTML or text body (if set) :+1:  I am currently working on some other things in Mailpit, so I'll leave this open and hopefully be able to implement this within the next few days. Thanks for the suggestion.

**Comment by nztim** [comment]
Thanks that's great, looking forward to it.

**Comment by axllent** [comment]
Thank you again for the suggestion. This feature has been added and released as part of v1.5.0. When viewing an email, click the "Download" button and select "HTML body". Please can you confirm this works for you as expected?

**Comment by nztim** [comment]
I just updated and it works perfectly. Thanks very much for implementing it!

**Comment by axllent** [comment]
You are welcome!
