### ISSUE TITLE
JavaScript error when adding the first tag manually

### ISSUE THREAD

**Issue by ocean90** [axllent/mailpit#68]
To reproduce:

* Get an email
* Open the email
* Enter a tag and press <kbd>Enter</kbd>

You'll be stuck with a loading animation and the browser console has these two errors:

<img width="567" alt="Bildschirm­foto 2023-03-21 um 14 46 24" src="https://user-images.githubusercontent.com/617637/226625451-8fbbe636-a999-4047-b807-2460645b718d.png">

Using v1.4.0 and latest Chrome version.

**Comment by axllent** [comment]
Thank you for reporting this, I will investigate as to why this is happening and fix it as soon as I'm able to.

**Comment by axllent** [comment]
Thank you again for reporting this. This fix has now been released as part of v1.5.0.

**Comment by ocean90** [comment]
Thanks!
