### ISSUE TITLE
ERROR  0.0.0.0:1025: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

### ISSUE THREAD

**Issue by isaacdarcilla** [axllent/mailpit#70]
I got this error when running `mailpit` command in PS (Windows).

```bash
PS C:\Users\Isaac> mailpit
INFO[2023/03/22 17:32:34] [smtp] starting on 0.0.0.0:1025
INFO[2023/03/22 17:32:34] [http] starting server on http://0.0.0.0:8025/
ERRO[2023/03/22 17:32:34] listen tcp 0.0.0.0:1025: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
```

How to resolve this?

**Comment by axllent** [comment]
Something else was/is running on your system in port 1025. If I had to take a guess you were/are running MailHog too (they use the same default ports). Alternatively you maybe already started another instance of Mailpit before which was still running at the time.
