### ISSUE TITLE
Easily view email headers

### ISSUE THREAD

**Issue by stef1904berg** [axllent/mailpit#71]
Is it possible to add a section to the email information that shows the headers sent with the email?

There already is an endpoint of the api that allows you to retrieve the headers (`api/v1/message/<ID>/headers`) but its not used in the webUI.
Being able to easily inspect the headers would be very useful as searching for them in the raw email can be difficult.

**Comment by axllent** [comment]
Clicking on the "Raw" tab in the web UI displays the message source, starting with the headers. Is that not sufficient as it displays the actual headers in their original format? If not, then can you please explain why?

The API endpoint was added for other purposes (automated testing), and extracting the headers and grouping by header type programmatically isn't an accurate indication as you loose the header order and their formatting.

**Comment by axllent** [comment]
I have just added this feature in v1.5.2. Please try it and confirm it works for you as expected, thanks.

**Comment by axllent** [comment]
I'm closing this issue as it has been three weeks since this feature was added.
