### ISSUE TITLE
Healthcheck endpoint

### ISSUE THREAD

**Issue by IgnisDa** [axllent/mailpit#73]
Hello, awesome project! Could a healthcheck endpoint be added? Just an endpoint that can be used to check if the service is healthy. It is useful in docker-compose etc.

**Comment by axllent** [comment]
Hi @IgnisDa . There are actually already two kubernetes-specific handlers which should both work for what you want, namely `http://localhost:8025/livez` or `http://localhost:8025/readyz`. I was considering adding this to the Dockerfile, however it would only work if using the default 8025 port and HTTP - if the user specifies another port or TLS via either an environment variable or command-line option it would fail, so I haven't implemented this.

Does this help?

**Comment by IgnisDa** [comment]
Yep it does work. Would be worth documenting them on https://github.com/axllent/mailpit/tree/develop/docs/apiv1.

**Comment by axllent** [comment]
Thanks for the feedback. Actually any of those API calls should technically work too. Given that this isn't necessarily an API-related feature but more of a system-related feature, I have now documented them in the [Wiki](https://github.com/axllent/mailpit/wiki/Healthcheck-endpoints) :+1:

**Comment by 99linesofcode** [comment]
Perhaps it would be more obvious to others but I quickly checked here to determine that the endpoint is exposed on the dashboard and not on the mailpit service itself.  Might be worth mentioning in the documentation.
