### ISSUE TITLE
Configuring the Tool

### ISSUE THREAD

**Issue by FuckingToasters** [axllent/mailpit#75]
Hello, I've installed it sucessfully and are able to view the dashboard (not tried smtp so far)
Now i would like to secure the smtp server auth auth credentials and specify an email it is going to send messages from.
For this i would need an configuration file but couldn't locate one in the directory.

**Comment by axllent** [comment]
@FuckingToasters - as @nosovk has pointed out, Basic Auth can easily be configured as per the documentation he linked to. 

I am not sure however what you mean with "and specify an email it is going to send messages from". Mailpit does not currently send any email, it just receives email. There is an open request for this functionality (to be able to "release" email), however this is a "wishlist feature" which has not been implemented yet.

**Comment by FuckingToasters** [comment]
> @FuckingToasters - as @nosovk has pointed out, Basic Auth can easily be configured as per the documentation he linked to.
> 
> I am not sure however what you mean with "and specify an email it is going to send messages from". Mailpit does not currently send any email, it just receives email. There is an open request for this functionality (to be able to "release" email), however this is a "wishlist feature" which has not been implemented yet.

It defently is able to send mails or why else would it specify smtp in the readme and show a sendmail keyword? smtp is for sending mails while imap is for reciving them.

**Comment by FuckingToasters** [comment]
> https://github.com/axllent/mailpit/wiki/Basic-authentication check doc please

and i don't really understand that, what file type do i need to supply? .txt, .anything etc.?

**Comment by axllent** [comment]
It sounds like there is some confusion here: either I am not understanding your issue, or you generally do not understand how email is usually sent from a system. 

There is a sendmail option provided for convenience which allows the running system to "send" emails to the running Mailpit server. You do not have to use that option, and any regular sendmail-compatible binary will work too provided they have been configured to send relay emails to localhost:1025 (Mailpit). Some applications (eg: Thunderbird) deliver emails directly to a SMTP server, so don't even use semdmail. Once the Mailpit server receives the email, the emails themselves never leave (it captures them). 

Sendmail itself does not decide the sender's email address, this is something that should be encoded into the email header that is being passed to it, together with the rest of the email. This means that a properly formatted email (which neither semdmail, not Maillot is relatie for) gets passed through to semdmail. This is standard for all MTA (Mail Transfer Applications), which simply pass on mail to a SMTP server (in this case Mailpit).

Lastly, the credential file is just a plain text file named whatever you like, and written in the same format as in the documentation. There are examples in the documentation which use the `user:password` format(in plain text) which is the easiest to use, but there is the option to use encrypted passwords is you know what you are doing.

If this does not answer your question, then please explain in more detail what you are trying to do, and what is not working for you, including what is generating the emails, and how are they currently being passed to semdmail / Maillot?
