### ISSUE TITLE
HTML and HTML Source tabs not available

### ISSUE THREAD

**Issue by IgnisDa** [axllent/mailpit#78]
@axllent Can this issue be re-opened? I get the same problem. I can not see the tabs both in firefox and chrome.

Firefox:
![image](https://user-images.githubusercontent.com/60938164/229171807-b2151584-c2f6-4afb-9826-a7a15b9956b8.png)

Chrome:

![image](https://user-images.githubusercontent.com/60938164/229171903-badc22ac-afdc-424b-bbce-fb65d8fce429.png)

I am using `1.5.1`.

Edit:

I tried to open it in incognito firefox with all extensions disabled but that did now work.

_Originally posted by @IgnisDa in https://github.com/axllent/mailpit/issues/24#issuecomment-1492194489_

**Comment by IgnisDa** [comment]
Moreover the Download button just has 2 options:

![image](https://user-images.githubusercontent.com/60938164/229176489-656b8351-1023-455d-abef-e778af180d16.png)

**Comment by axllent** [comment]
@IgnisDa I do not believe this is the same issue as the other ticket (#24), as that one showed the tabs, yours does not show either button.

Also, the errors you see in Firefox also do not appear to be coming from the email in the screenshot, but rather another email.

If I had to take an initial guess here, I would say that there is actually no valid HTML part in your email at all (hence why it is not showing), and that the email itself is encoding the html as the plain text body. The only way I can be sure is if you would be willing to attach the entire message to this issue (download and zip it up).

**Comment by IgnisDa** [comment]
@axllent I was sending the email wrong from my application, my bad. I was just sending the plaintext email, not HTML. This is now fixed.

**Comment by robisadev** [comment]
> @axllent I was sending the email wrong from my application, my bad. I was just sending the plaintext email, not HTML. This is now fixed.

This lead me to the promised land and fixed all my woes.
