### ISSUE TITLE
Harddrive storage size

### ISSUE THREAD

**Issue by Florent4782** [axllent/mailpit#8]
Hi,

first of all, a big thank you for your amazing work !

It is not necessarily a big issue, but I find a bit weird that I got a 2GB+ file in the storage directory while there is only 4 emails... with small attachments.

![image](https://user-images.githubusercontent.com/66121810/185228940-12d0e0e4-6668-4c27-aaaf-a61c40b3cb40.png)
![image](https://user-images.githubusercontent.com/66121810/185229211-647ef2aa-865a-4556-b25f-e6ffd23d0d54.png)

**Comment by Florent4782** [comment]
Ok, I saw in the issue #3 that it is a temporary file from CloverDB. I feel like it's huge. Is there any way we can decrease this size ? or the file to "autogrow" ?

**Comment by axllent** [comment]
@Florent4782 Thanks for the appreciation and feedback. This confused me at first too, but it is an internal BadgerDB (the underlying database that CloverDB uses) memory-mapping file. On Linux (I'm not 100% sure about Windows), this file looks like a physical file but it doesn't actually take up any physical space (`du -hs <folder>` returns the total size minus the 2GB).

**Comment by axllent** [comment]
To follow on from this, CloverDB/BadgerDB does use more memory (even when saving to disk) than I would like. Ideally this would be far less, however I've put that into the "too hard basket" as it would mean a large change to Mailpit, as I would probably have to choose another database altogether. CloverDB (functionality-wise) does exactly what I need it to, and I wasn't able to find another similar solution (that didn't involve a hosted database server which I do not want).

**Comment by Florent4782** [comment]
OK, I understand. 
Let me just ask a question though with my little development knowledge: what about SQLite ? 

Will let you know about what real size it takes on Windows.

**Comment by axllent** [comment]
SQLite has two main issues - normally it requires CGO (not native to Go) which is horrible for cross-platform binaries. There is now a "native" Go version for SQLite, however I don't think it's yet production-ready. Secondly, SQLite is not suitable re: speed/performance (imagine storing 10k full emails - or 5GB of data in a single SQLite file). I did look at this initially when choosing a database and decided against it :)

**Comment by axllent** [comment]
@Florent4782 Just to keep you in the loop - after finding a native Go SQL library, I have been trialling SQLite here with very promising results ~ even with a database containing 300k emails / 7.7GB (which is far more than anyone would every have but still...). This addresses several issues too, including storage and memory usage. I still have more extensive testing to do first, but so far so good!

**Comment by Florent4782** [comment]
@axllent, from a user's perspective this appears to be a good move ! Mailpit starts much faster (I guess because it doesn't have to write the 2GB file), and indeed memory usage is much small too !
Just as confirmation, the 2GB file seemed real on Windows:
![image](https://user-images.githubusercontent.com/66121810/187439088-d5f026e0-a5ba-4d24-9e8a-8a60eeed1e33.png)

I did some tests with attachments and this seems great. 
It may be a good idea to "VACCUM" the db file on closing Mailpit. I noticed it doesn't seem to be the case now.

**Comment by axllent** [comment]
@Florent4782 Thanks for the feedback, I'll consider this issue resolved then :+1: 

Regarding running a `VACUUM` when the application exists - VACUUM takes time and is processor-intensive (the entire database is compacted and rewritten). This would mean that existing the application could take 30 - 60 seconds which isn't good, especially if running Mailpit within docker (which will by default kill running processes after 30 seconds or so). VACUUM is also only useful when there are deleted messages, and currently runs automatically when:
1. immediately after a `Delete all` has happened, or
2. If there are deleted messages, and only after 5 minutes of database inactivity - to try make sure it's just running idle and not being used at the same time. SQLite isn't good at multiple connections or actions at the same time, so everything will "freeze" while the VACUUM is running.
