### ISSUE TITLE
Docker version tag for major/minor version branch

### ISSUE THREAD

**Issue by ocean90** [axllent/mailpit#82]
Right now the Docker images are only available via the `latest` and the specific version tags. It would be helpful to be able to only define `axllent/mailpit:v1.5` which would pull the latest version of the `1.5` branch. That would be `1.5.4` at the moment.

It seems like this only needs a change to https://github.com/axllent/mailpit/blob/8e84b96233ef7f60a11695557776be521c875319/.github/workflows/build-docker.yml#L34

Maybe the [docker/metadata-action](https://github.com/docker/metadata-action) action will be useful: https://github.com/docker/metadata-action#typesemver

**Comment by axllent** [comment]
Thanks for the suggestion, this is a good idea.  I think that the docker/metadata-action is probably an overkill as it is designed to also push images (I just need to work out that the major.minor version is), so I'm going to try another simpler action first. Assuming this works (you never know until you try), the next release should include a `mailpit:v1.5` tag :+1: I will leave this open until the next release (which are fairly regular).

**Comment by ocean90** [comment]
Sounds good! I don't think it will be push stuff as it only provides an output for the metadata which can be used by the push action. The readme has a good example for this.

**Comment by axllent** [comment]
I've tested this on a separate testing repo and the action I am using to detect the major/minor version is working as expected. Given there are no current changes it may be a while before another release, so in the interim I have manually pushed a v1.5 tag (identical currently to v1.5.4) so you can start using that already if you like. When newer v1.5.* releases are created, the v1.5 tag will be updated, then v.16 will get added and updated etc when the release tags reach v1.6.* etc.

I'll close this ticket as it is effectively done now (just waiting for more releases). Thanks again for the suggestion.
