### ISSUE TITLE
Multiple inboxes

### ISSUE THREAD

**Issue by Mint1700** [axllent/mailpit#86]
I wanted to know if multiple inboxes is something that would be in available in mailpit.

I would like to use multiple smtp user/password to send mails that can be viewed in the ui by differents users. Maybe with an automatic tag or something like that, I don't know if this possible.

Thanks.

**Comment by axllent** [comment]
Hi @Mint1700 . No sorry, this is not in the planning, nor possible with Mailpit. Whilst Mailpit does support multiple SMTP & UI logins, it all has a single (same) mailbox. You could run multiple instances on Mailpit to listen on different ports, and then configure each of the applications to the respective ports, but that's about as far as you'll get.
