### ISSUE TITLE
Message delete using curl on windows

### ISSUE THREAD

**Issue by gitgrub** [axllent/mailpit#88]
Hello,

I have a problem deleting a single message using curl.
Using the "try" button in the api doc works.
But using the curl method deletes all messages. My curl command is:
`
curl -X DELETE "http://127.0.0.1:8025/api/v1/messages" -H "content-type: application/json" -d '{"ids":["505597d0-1367-456b-8690-b957dde261bb"]}'
`

Actually using python with your api, but trying to delete a message deleted all of them. So I thought I am doing something wrong, that's why I used curl for a test.

What am I doing wrong?

**Comment by axllent** [comment]
That is strange. I have just tested with `curl -X DELETE "http://127.0.0.1:8025/api/v1/messages" -H "content-type: application/json" -d '{"ids":["fb368984-a7bb-41d8-9971-222f8dda46b8"]}'` and it works exactly as expected, and only message `fb368984-a7bb-41d8-9971-222f8dda46b8` was deleted.

Are you 100% sure the messages weren't already deleted before you tried the curl command? The only time all messages will be deleted is if a blank array of `ids` (or no ids at all) are defined as valid JSON in your data. If an ID is set but doesn't exist, then nothing is deleted (eg: `{"ids":["thisdoesntexist"]}`).

**Comment by axllent** [comment]
That is so strange. Can you please try the following for me, and post the response (leaving out your "origin" ip address):

```
curl -X DELETE "https://httpbin.org/anything/test" -H "content-type: application/json" -d '{"ids":["1234-5678-0000"]}'
```

which should return something like:
```json
{
  "args": {}, 
  "data": "{\"ids\":[\"1234-5678-0000\"]}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "26", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.81.0", 
    "X-Amzn-Trace-Id": "Root=1-64362972-1eec1de5411d2cd75aecc5dc"
  }, 
  "json": {
    "ids": [
      "1234-5678-0000"
    ]
  }, 
  "method": "DELETE", 
  "origin": ".....", 
  "url": "https://httpbin.org/anything/test"
}
```

**Comment by gitgrub** [comment]
Result is:
`
{
  "args": {}, 
  "data": "'{ids:[1234-5678-0000]}'", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "24", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/8.0.1", 
    "X-Amzn-Trace-Id": "Root=1-64362a8a-397e67a9458880ec3b1674cd"
  }, 
  "json": null, 
  "method": "DELETE", 
  "origin": "out", 
  "url": "https://httpbin.org/anything/test"
}
`

Sorry for the ugly non line breaks.

**Comment by gitgrub** [comment]
Funny, did the same from a linux laptop, now json is here:
```
$ curl -X DELETE "https://httpbin.org/anything/test" -H "content-type: application/json" -d '{"ids":["1234-5678-0000"]}'
{
  "args": {}, 
  "data": "{\"ids\":[\"1234-5678-0000\"]}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "26", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.74.0", 
    "X-Amzn-Trace-Id": "Root=1-64362cfd-0cfd62e91ae46aff36c23958"
  }, 
  "json": {
    "ids": [
      "1234-5678-0000"
    ]
  }, 
  "method": "DELETE", 
  "origin": "out", 
  "url": "https://httpbin.org/anything/test"
}
```

**Comment by gitgrub** [comment]
Oh hell, happy win shell quoting, on win we need:
```
D:\winprog\mailpit\curl>curl -X DELETE "https://httpbin.org/anything/test" -H "content-type: application/json" -d "{\"ids\":[\"1234-5678-0000\"]}" 
{
  "args": {}, 
  "data": "{\"ids\":[\"1234-5678-0000\"]}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "26", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/8.0.1", 
    "X-Amzn-Trace-Id": "Root=1-643631cd-0ba95f3e598d78ad6d86ea8f"
  }, 
  "json": {
    "ids": [
      "1234-5678-0000"
    ]
  }, 
  "method": "DELETE", 
  "origin": "91.118.140.33", 
  "url": "https://httpbin.org/anything/test"
}
```

**Comment by axllent** [comment]
That is interesting indeed, bloody Windows. It looks like you have uncovered the issue, although I do not know what to do about it in the docs unfortunately. The Swagger documentation is generated on-the-fly in the browser using [RapidDoc](https://github.com/rapi-doc/RapiDoc) which doesn't appear to have an option for that. You could potentially open a bug report there?

**Comment by gitgrub** [comment]
Done: https://github.com/rapi-doc/RapiDoc/issues/918
My real issue was access via python, there is a lot of discussion on stackoverflow that a body with delete command is not well defined, some servers seem to turn it into a put request, others like google just reject it. Idk, did not test this.

The hint for python users for the requests.delete command, is not to use the data parameter (which will be empty, killing all messages), but the json parameter. Now we can delete a single message.

In general: maybe it would be good not to delete all messages if the ids array is empty or not defined.
I do not know how apis like that work, but would imagine something like ids:[all] or [*].

**Comment by axllent** [comment]
Thanks. I'm following that thread, and if they implement a work-around I will implement it. In the meantime the "issue" lies there (and Windows) and there is nothing further I can do here unfortunately.

> PS: in that context, so no extra issue: The web UI is not updated after a delete operation via api. Maybe use a timeout to not fire too many page refreshes on mass deletion?

I hear you, but this is a separate issue, and to be honest it's not something on my TODO list right now. If I am going to notify on deletions, then why not changed read statuses, tags etc... it quickly blows out into a full-featured webmail client with everything but actual emailing :-) The point is that creating a multi-browser synced mailbox (for all actions) adds a huge development overhead, and isn't an easy thing to do (correctly) - all for very little benefit. Sure, it would be great if the UI updated if a separate API request deletes or modifies something, but that's really just a nice-to-have for a small subset of users I feel.

**Comment by gitgrub** [comment]
Yes that's right, lets forget about the update thing.
