### ISSUE TITLE
Notification support

### ISSUE THREAD

**Issue by fridzema** [axllent/mailpit#89]
Should be nice if we can get a [notification](https://developer.mozilla.org/en-US/docs/Web/API/Notification). 
If you are open for a pull request, i can try to implement in the near future.

**Comment by Fydon** [comment]
My browser (Edge) is set to ask for notification permission, but I wasn't prompted to allow it when selecting the bell icon. However when I used site settings to allow the notification permission, I started receiving notifications. I was already using HTTPS for Mailpit.

**Comment by axllent** [comment]
@Fydon It seems Edge was having a race issue between running that request (for notifications) and closing the modal. I have pushed a fix for this which will be included in the next release (in the next few days). Thanks for reporting.

**Comment by axllent** [comment]
@Fydon The fix has been included in [v1.12.2](https://github.com/axllent/mailpit/releases/tag/v1.21.2).
