### ISSUE TITLE
Enable as a service on linux

### ISSUE THREAD

**Issue by ameerElsherif** [axllent/mailpit#94]
How can I use mailpit as a service, so it can be enabled and automatically run with system start?
I am used to having this with Mailhog so, it is always running in the background.
So, I am not very comfortable having to run the command in a terminal every time I need to use mailpit.

**Comment by axllent** [comment]
Hi. Can you please explain to me how you installed and are running MailHog on your system automatically? Did you follow some documentation to get this working, and if so, where did you see that documentation? Lastly, what system are you referring to, Windows, Linux or Mac?

**Comment by axllent** [comment]
That appears to be specifically an Arch Linux package created for MailHog, and would include additional startup scripts designed for Arch. You will need to ask a maintainer (of Arch Linux packages) if they would be willing to include Mailpit in their packages. I do not know where you would ask that as I don't use Arch, but that site looks like a good starting point.

**Comment by ameerElsherif** [comment]
For anyone interested in this, I ended up accomplishing it by creating a file with the following content:

`
[Unit]
Description=Mailpit
Documentation=https://github.com/axllent/mailpit
After=syslog.target network.target
AssertFileIsExecutable=/usr/local/bin/mailpit

[Service]
User=nobody
ExecStart=/usr/local/bin/mailpit
ExecReload=/bin/kill -USR2 $MAINPID

[Install]
WantedBy=multi-user.target
`

- You should change mailpit path if it is different than "/usr/local/bin/mailpit"
- The location to save the file can be different for different systems you should lookup which path will work for you. For me on arch linux using systemd it was "/usr/lib/systemd/system/mailpit.service"

After creating the service file, run the following commands:
`sudo systemctl start mailpit`
`sudo systemctl enable mailpit`

Done!
