### ISSUE TITLE
Add volume mount for docker example

### ISSUE THREAD

**Issue by liayn** [axllent/mailpit#95]
The example to run the docker image is incomplete when it comes to authentication.

Currently the example reads like this:
```
docker run -d \
--name=mailpit \
--restart unless-stopped \
-e MP_DATA_FILE=/mailpit/mailpit.db \
-e MP_UI_AUTH_FILE=/mailpit/authfile \
-e TZ=Europe/London \
-p 8025:8025 \
-p 1025:1025 \
axllent/mailpit
```

But it lacks any means to actually provide the referenced `/mailpit/authfile` inside the container.

I think it should be extended to:

```
docker run -d \
--name=mailpit \
--restart unless-stopped \
-v some/path/to/authfile:/mailpit/authfile
-e MP_DATA_FILE=/mailpit/mailpit.db \
-e MP_UI_AUTH_FILE=/mailpit/authfile \
-e TZ=Europe/London \
-p 8025:8025 \
-p 1025:1025 \
axllent/mailpit
```

(or something similar)

**Comment by axllent** [comment]
You're absolutely right! Thanks, I've updated the wiki. Thank you.
